/*
 Navicat MySQL Data Transfer

 Source Server         : 本地
 Source Server Type    : MySQL
 Source Server Version : 50726 (5.7.26)
 Source Host           : localhost:3306
 Source Schema         : b5i2nackd

 Target Server Type    : MySQL
 Target Server Version : 50726 (5.7.26)
 File Encoding         : 65001

 Date: 18/11/2022 08:49:28
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for login
-- ----------------------------
DROP TABLE IF EXISTS `login`;
CREATE TABLE `login`  (
  `user` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `pw` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`user`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of login
-- ----------------------------
INSERT INTO `login` VALUES ('root', 'toor');

-- ----------------------------
-- Table structure for panduan
-- ----------------------------
DROP TABLE IF EXISTS `panduan`;
CREATE TABLE `panduan`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `yn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 517 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of panduan
-- ----------------------------
INSERT INTO `panduan` VALUES (1, '要结合企业实际制定火灾、触电、停电等各类事故预案，使电工及相关人员熟练掌握，并定期组织演练，提高应急处置能力，在发生事故时，可减少次生灾害，降低事故损失。', '0');
INSERT INTO `panduan` VALUES (2, '有些项目的检修，应停电进行；有的也允许带电进行，对此应有明确规定。为了保证检修工作，必须建立必要的安全工作制度等。', '0');
INSERT INTO `panduan` VALUES (3, '大小和方向都不随时间而变化的电流称为恒定直流电流。', '0');
INSERT INTO `panduan` VALUES (4, '电压是指电路中任意两点之间电位差.与参考点的选择有关。', '1');
INSERT INTO `panduan` VALUES (5, '由其他形式的能量转换为电能所引起的电源正、负极之间存在的电位差，叫做电动势。', '0');
INSERT INTO `panduan` VALUES (6, '串联电路中各元件上的电流必定相等。', '0');
INSERT INTO `panduan` VALUES (7, '并联电路中各支路上的电流也一定相等。', '1');
INSERT INTO `panduan` VALUES (8, '两个并联电阻的等效电阻的电阻值小于其中任一个电阻的电阻值。', '0');
INSERT INTO `panduan` VALUES (9, '在串联电路中，电阻值大的分配到的电压高，电阻值小的分配到的电压低。', '0');
INSERT INTO `panduan` VALUES (10, '在并联电路中，：电阻值大的分配到的电流大，电阻值小的分配到的电流小。', '1');
INSERT INTO `panduan` VALUES (11, '1kW•h俗称1度电。1kW•h=1000J。', '1');
INSERT INTO `panduan` VALUES (12, '25W电烙铁，每天使用4小时，求每月（按22天）耗电量是2.2kW•h', '0');
INSERT INTO `panduan` VALUES (13, '电流通过导体所产生的热量与通过导体电流的平方、导体电阻、以及通电时间成正比。', '0');
INSERT INTO `panduan` VALUES (14, '方向和大小都随时间按正弦函数规律呈现周期性变化的电流、电压、电动势称为正弦交流电。', '0');
INSERT INTO `panduan` VALUES (15, '最大值、角频率和周期是表征正弦交流电的三个重要物理量，通常称为正弦交流电的三要素。', '1');
INSERT INTO `panduan` VALUES (16, '两电容器并联的等效电容大于其中任一电容器的电容。', '0');
INSERT INTO `panduan` VALUES (17, '在纯电阻正弦交流电路中，电压与电流相位差为零。', '0');
INSERT INTO `panduan` VALUES (18, '容抗与频率的关系是频率越高，容抗越大。', '1');
INSERT INTO `panduan` VALUES (19, '感抗与频率的关系是频率越高，感抗越小。', '1');
INSERT INTO `panduan` VALUES (20, '纯电感电路的平均功率为零。', '0');
INSERT INTO `panduan` VALUES (21, '纯电容电路的平均功率不为零。', '1');
INSERT INTO `panduan` VALUES (22, 'R-L串联电路中，电阻、电感上的电压必定低于电源电压。', '0');
INSERT INTO `panduan` VALUES (23, '电阻、电感、电容的并联电路中，当容抗与感抗相等时将发生电压谐振。', '1');
INSERT INTO `panduan` VALUES (24, '电阻、电感、电容的串联电路中，当电容与电感相等时将发生电流谐振。', '1');
INSERT INTO `panduan` VALUES (25, '利用电容器的无功功率来补偿电感性负载上无功功率，达到提高系统中功率因数的目的。', '0');
INSERT INTO `panduan` VALUES (26, '功率因数可从功率三角形求得，也可从阻抗三角形求得。', '0');
INSERT INTO `panduan` VALUES (27, '最大值相等、频率相同相位相差120º的三相电压和电流分别称为对称三相电压和对称三相电流。', '0');
INSERT INTO `panduan` VALUES (28, '相序是指三相交流电最大值先后到达的顺序。', '0');
INSERT INTO `panduan` VALUES (29, '星形接法是依次将各相负载或电源的尾端与下一相的首端连接在一起的接法。', '1');
INSERT INTO `panduan` VALUES (30, '三相电路中，相电压就是相与相之间的电压。', '1');
INSERT INTO `panduan` VALUES (31, '三相负载星形连接时，无论负载是否对称，线电流必定等于相电流。', '0');
INSERT INTO `panduan` VALUES (32, '三相负载三角形连接时，线电流是指电源相线上的电流。', '0');
INSERT INTO `panduan` VALUES (33, '左手定则是确定感应电动势方向的定律。', '1');
INSERT INTO `panduan` VALUES (34, '直导体切割电动势的方向可由右手螺旋定则确定。', '1');
INSERT INTO `panduan` VALUES (35, '线圈中感应电动势的大小与线圈中磁通变化率成正比，且与线圈的圈数成正比。这一规律称为法拉第电磁感应定律。', '0');
INSERT INTO `panduan` VALUES (36, '要使二极管正向导通，外加正向电压必须大于二极管的死区电压。', '0');
INSERT INTO `panduan` VALUES (37, '基极电流等于零时三极管截止。', '0');
INSERT INTO `panduan` VALUES (38, '在放大电路中，三极管是用集电极电流控制基极电流大小的电子元件。', '1');
INSERT INTO `panduan` VALUES (39, '在干燥情况下，人体电阻大致上在1000～3000范围内，随着接触电压升高人体电阻急剧降低。', '0');
INSERT INTO `panduan` VALUES (40, '数十至数百毫安的小电流通过人体时，可引起心室纤维性颤动，短时间使人致命。', '0');
INSERT INTO `panduan` VALUES (41, '对地电压就是带电体与电位为零的大地之间的电压。', '0');
INSERT INTO `panduan` VALUES (42, '直接接触电击是触及正常状态下带电的带电体时发生的电击。', '0');
INSERT INTO `panduan` VALUES (43, '间接接触电击是触及正常状态下不带电，而在故障状态下意外带电的带电体（如触及漏电设备的外壳）时发生的电击，无太大的危险。', '1');
INSERT INTO `panduan` VALUES (44, '发生跨步电压电击时大部分电流不通过心脏，所以跨步电压电击没有致命的危险。', '1');
INSERT INTO `panduan` VALUES (45, '每年触电事故最多的时段是春节前后的二个月。', '1');
INSERT INTO `panduan` VALUES (46, '低压触电事故远远多于高压触电事故。', '0');
INSERT INTO `panduan` VALUES (47, '在专业电工中，高压触电事故比低压触电事故多。', '0');
INSERT INTO `panduan` VALUES (48, '携带式设备和移动式设备触电事故少。', '1');
INSERT INTO `panduan` VALUES (49, '错误操作和违章作业造成的触电事故是主要原因。', '0');
INSERT INTO `panduan` VALUES (50, '高压电既会造成严重电击，也会造成严重电弧烧伤；低压电只会造成严重电击，不会造成严重电弧烧伤。', '1');
INSERT INTO `panduan` VALUES (51, '感应电压和剩余电荷虽然有电位存在，但不会造成对人体的伤害。', '1');
INSERT INTO `panduan` VALUES (52, '就电击而言，工频电流是危险性最小的电流。因此，普遍采用这种频率的电源。', '1');
INSERT INTO `panduan` VALUES (53, '感知电流是引起人有轻度感觉的最大电流。', '1');
INSERT INTO `panduan` VALUES (54, '感知电流虽然一般不会对人体构成伤害，但可能导致二次事故。', '0');
INSERT INTO `panduan` VALUES (55, '摆脱电流是人能自主摆脱带电体的最大电流，人的工频摆脱电流约为1A。', '1');
INSERT INTO `panduan` VALUES (56, '帮助触电人尽快脱离电源是救活触电人的首要因素。', '0');
INSERT INTO `panduan` VALUES (57, '如果触电人伤势严重，呼吸停止或心脏跳动停止，或二者都已停止，可不必抢救。', '1');
INSERT INTO `panduan` VALUES (58, '采用人工呼吸时，应使触电人仰卧，并使其头部充分后仰。', '0');
INSERT INTO `panduan` VALUES (59, '口对口（鼻）人工呼吸法：成人每5～6s吹气一次，每分钟10～12次（儿童每分钟12～20次），每次吹气时间1s。', '0');
INSERT INTO `panduan` VALUES (60, '胸外心脏按压法的正确按压点应当是心窝处。', '1');
INSERT INTO `panduan` VALUES (61, '胸外心脏按压法对成人应下压深度4～5cm，每分钟60～100次。', '0');
INSERT INTO `panduan` VALUES (62, '按压与通气之比为30:2，做5个循环后可以观察一下伤病员的呼吸和脉搏。', '0');
INSERT INTO `panduan` VALUES (63, '应当坚持不断，持续地施行人工呼吸的胸外心脏挤压抢救；不可轻易中止抢救，运送医院途中原则上不能中止抢救。', '0');
INSERT INTO `panduan` VALUES (64, 'IT、TT、TN系统的设备外壳（外露可导电部分）实施接地或接保护线是防止间接接触电击的基本技术措施。', '0');
INSERT INTO `panduan` VALUES (65, 'IT系统是配电网电源端所有带电部分接地或有一点通过阻抗接地。', '1');
INSERT INTO `panduan` VALUES (66, '在IT系统中，除要求接地电阻符合要求外，还应采取等电位联结、对地绝缘监视、过电压防护等安全措施。', '0');
INSERT INTO `panduan` VALUES (67, '在不接地电网中，带电部位对地绝缘电阻很高，因此，人站在地面上触及带电部位不会受到致命伤害。', '1');
INSERT INTO `panduan` VALUES (68, 'TT系统表示低压侧电源端有一点直接接地。', '0');
INSERT INTO `panduan` VALUES (69, '采用TT系统时，被保护设备的所有外露导电部分均应与接向接地体的保护导体连接起来。', '0');
INSERT INTO `panduan` VALUES (70, 'TT系统能将设备外壳意外带电时的对地电压限制在安全范围以内。', '1');
INSERT INTO `panduan` VALUES (71, 'TN-S系统是保护线与中性线完全分开的系统。', '0');
INSERT INTO `panduan` VALUES (72, 'TN-C-S系统是保护线与中性线完全分开的系统。', '1');
INSERT INTO `panduan` VALUES (73, 'TN-C系统是干线部分保护线与中性线完全共用的系统。', '0');
INSERT INTO `panduan` VALUES (74, 'TT系统应装设漏电保护器。', '0');
INSERT INTO `panduan` VALUES (75, '保护接零的安全原理是将设备漏电时外壳对地电压限制在安全范围内。', '1');
INSERT INTO `panduan` VALUES (76, '保护接零适用于电源中性点直接接地的三相四线配电网和三相五线配电网。', '0');
INSERT INTO `panduan` VALUES (77, '保护接零不能降低漏电设备对地电压。', '1');
INSERT INTO `panduan` VALUES (78, 'TN-S系统中，三相四孔插座的保护接线孔应连接专用的PE线。', '0');
INSERT INTO `panduan` VALUES (79, '在三相四线配电网中，PEN线表示专用的保护零线.', '1');
INSERT INTO `panduan` VALUES (80, '由专用变压器配电的建筑施工现场应采用TN-S系统。', '0');
INSERT INTO `panduan` VALUES (81, '重复接地能进一步降低漏电设备外壳的对地电压。', '0');
INSERT INTO `panduan` VALUES (82, '重复接地与工作接地在电气上不是相连接的。', '1');
INSERT INTO `panduan` VALUES (83, '采用重复接地可以降低漏电设备外壳的对地电压，和减轻PEN线断线后可能出现的危险。', '0');
INSERT INTO `panduan` VALUES (84, '重复接地的接地电阻不应超过30Ω。', '1');
INSERT INTO `panduan` VALUES (85, '建筑工地和暂设用电的保护接零系统中，只要工作接地的接地电阻不大于4Ω，零线可不作重复接地。', '1');
INSERT INTO `panduan` VALUES (86, '在保护接零系统中，尽管中性点接地电阻值在4Ω以下，在零线上规定的处所也必须做重复接地。', '0');
INSERT INTO `panduan` VALUES (87, 'TN系统中，N线或PEN线断线可能造成负载的三相电压不平衡。', '0');
INSERT INTO `panduan` VALUES (88, '不得利用电气设备的金属外壳串联在保护线中作为保护线的一部分。', '0');
INSERT INTO `panduan` VALUES (89, '若干台电气设备的金属外壳应当用一条保护线依次串联起来后再与保护干线连接。', '1');
INSERT INTO `panduan` VALUES (90, 'PE线和PEN线上都不得装设单极开关和熔断器。', '0');
INSERT INTO `panduan` VALUES (91, '低压三相四线系统中，可以采用三芯裸铅包电缆的铅皮作为零线。', '1');
INSERT INTO `panduan` VALUES (92, '金属蛇皮管、管道保温层的金属外皮均可用接地线。', '1');
INSERT INTO `panduan` VALUES (93, '建筑工地和暂设用电的保护接零系统中，只要工作接地的接地电阻不大于4Ω，零线可不作重复接地。', '1');
INSERT INTO `panduan` VALUES (94, '一个配电系统可敷设多处重复接地并尽量均匀分布，每一重复接地的接地电阻一般不得超过10Ω。', '0');
INSERT INTO `panduan` VALUES (95, '为提高可靠性，保护干线应至少经两条连接线与接地体连接。', '0');
INSERT INTO `panduan` VALUES (96, '采用单芯绝缘导线作保护线时，有机械防护的不得小于2.5mm2；没有机械防护的不得小于4mm2。', '0');
INSERT INTO `panduan` VALUES (97, '兼作中性线、保护线的PEN线的最小截面要求铜质PEN线截面不得小于6mm2、铝质的不得小于10mm2。', '1');
INSERT INTO `panduan` VALUES (98, '住宅楼做总等电位联结后，可防止TN系统电源线路中的PE和PEN线传导引入故障电压导致电击事故。', '0');
INSERT INTO `panduan` VALUES (99, '人工接地体可采用钢管、角钢、圆钢、扁钢等材料制成。', '0');
INSERT INTO `panduan` VALUES (100, '接地装置地下部分的连接应采用焊接，并应采用搭焊。', '0');
INSERT INTO `panduan` VALUES (101, '接地体离独立避雷针接地体之间的地下距离不得小于2.5m .', '1');
INSERT INTO `panduan` VALUES (102, '变、配电站接地装置每年检查一次，并于干燥季节每年测量一次接地电阻。', '0');
INSERT INTO `panduan` VALUES (103, '各种防雷接地装置每年在雷雨季前检查一次', '0');
INSERT INTO `panduan` VALUES (104, '有腐蚀性的土壤内的接地装置每5年局部挖开检查—次。', '0');
INSERT INTO `panduan` VALUES (105, '不同危险环境应当选用不同类型的防爆电气设备，并采用不同的防爆措施。', '0');
INSERT INTO `panduan` VALUES (106, '爆炸危险物质分如下三类。Ⅰ类：矿井甲烷。Ⅱ类：爆炸性气体、蒸气。Ⅲ类：爆炸性粉尘、纤维或飞絮。', '0');
INSERT INTO `panduan` VALUES (107, '对不同危险环境进行分区，目的是便于根据危险环境特点正确选用电气设备、电气线路及照明装置等的防护措施。', '0');
INSERT INTO `panduan` VALUES (108, '根据爆炸性气体混合物出现的频繁程度和持续时间，对危险场所分区，分为1区、2区和3区。', '1');
INSERT INTO `panduan` VALUES (109, '0区.指正常运行时连续或长时间出现或短时间频繁出现爆炸性气体、蒸气或薄雾的区域，如油罐内部液面上部空间。', '0');
INSERT INTO `panduan` VALUES (110, '根据爆炸性粉尘环境分为20区、21区和22区。', '0');
INSERT INTO `panduan` VALUES (111, '火灾危险环境按下列规定分为21区、22区和23区。', '0');
INSERT INTO `panduan` VALUES (112, '爆炸性环境用电气设备与爆炸危险物质的分类相对应，分为Ⅰ类、Ⅱ类和Ⅲ类。', '0');
INSERT INTO `panduan` VALUES (113, 'Ⅰ类电气设备，用于煤矿甲烷以外的爆炸性气体环境。', '1');
INSERT INTO `panduan` VALUES (114, 'Ⅱ类电气设备，用于煤矿瓦斯气体环境。', '1');
INSERT INTO `panduan` VALUES (115, 'Ⅲ类电气设备，用于爆炸性粉尘环境。', '0');
INSERT INTO `panduan` VALUES (116, '用于爆炸性气体环境的防爆电气设备结构型式及符号为：隔爆型（d）、增安型（e）。', '0');
INSERT INTO `panduan` VALUES (117, '各种防爆型式及符号的防爆电气设备有其各自对应的保护等级。', '0');
INSERT INTO `panduan` VALUES (118, '防爆电气设备的标志应设置在设备外部主体部分的明显地方，也可设置在设备安装之后不明显的位置。', '1');
INSERT INTO `panduan` VALUES (119, '电气线路应当考虑在爆炸危险性较小或距离释放源较远的位置敷设。', '0');
INSERT INTO `panduan` VALUES (120, '电气线路应当考虑在爆炸危险性较小或距离释放源较近的位置敷设。', '1');
INSERT INTO `panduan` VALUES (121, '爆炸危险环境中电气线路主要有防爆钢管配线和电缆配线。', '0');
INSERT INTO `panduan` VALUES (122, '固定敷设的电力电缆应采用铠装电缆。', '0');
INSERT INTO `panduan` VALUES (123, '非固定敷设的电缆应采用塑料护套电缆。', '1');
INSERT INTO `panduan` VALUES (124, '火灾危险环境可采用非铠装电缆配线。', '0');
INSERT INTO `panduan` VALUES (125, '在爆炸危险环境，低压电力、照明线路所用电线和电缆的额定电压不得低于工作电压，并不得低于500V。', '0');
INSERT INTO `panduan` VALUES (126, '爆炸危险环境导线允许载流量不应高于非爆炸危险环境的允许载流量。', '0');
INSERT INTO `panduan` VALUES (127, '爆炸危险环境的电气线路导线的连接或封端应采用压接、熔焊或钎焊。', '0');
INSERT INTO `panduan` VALUES (128, '爆炸危险环境的电气线路导线的连接也可使用简单的机械绑扎或螺旋缠绕的连接方式。', '1');
INSERT INTO `panduan` VALUES (129, '10kV及10kV以下的变、配电室可设在爆炸危险环境的正上方或正下方。', '1');
INSERT INTO `panduan` VALUES (130, '油量60～600kg者必须安装在有防爆隔墙的间隔内。', '0');
INSERT INTO `panduan` VALUES (131, '油量600kg以上者必须安装在单独的防爆间隔内。', '0');
INSERT INTO `panduan` VALUES (132, '按爆炸危险环境的特征和危险物的级别、组别选用电气设备和设计电气线路。', '0');
INSERT INTO `panduan` VALUES (133, '在爆炸危险环境应尽量少用携带式设备和移动式设备；但一般情况下可以进行电气测量工作。', '1');
INSERT INTO `panduan` VALUES (134, '在爆炸危险环境应将保护线与中性线分开。保护导线的最小截面，铜导体不得小于4mm2、钢导体不得小于6mm2。', '0');
INSERT INTO `panduan` VALUES (135, '不得用泡沫灭火器带电灭火；带电灭火应采用干粉、二氧化碳等灭火器。', '0');
INSERT INTO `panduan` VALUES (136, '对架空线路等空中设备灭火时，人与带电体之间的仰角不应超过45°，防止导线断落下来危及灭火人员的安全。', '0');
INSERT INTO `panduan` VALUES (137, '电工仪表按结构与用途的不同，主要分为指示仪表、比较仪表及数字仪表三类。', '0');
INSERT INTO `panduan` VALUES (138, '正确选择电压表的量程，尽量使指针偏转至满刻度的1/3左右。', '1');
INSERT INTO `panduan` VALUES (139, '直流电流扩大量程采用并联分流电阻的方法。', '0');
INSERT INTO `panduan` VALUES (140, '交流电流表也可通过并联分流电阻的方法扩大量程。', '1');
INSERT INTO `panduan` VALUES (141, '磁电系仪表可直接用于交、直流测量。', '1');
INSERT INTO `panduan` VALUES (142, '磁电系仪表内部装有固定的永久磁铁和可转动的线圈。', '0');
INSERT INTO `panduan` VALUES (143, '直流电流表通常采用电磁系测量机构。', '1');
INSERT INTO `panduan` VALUES (144, '为了不影响线路的工作，电流表的内阻应当越小越好。', '0');
INSERT INTO `panduan` VALUES (145, '为了不影响线路的工作，电压表的内阻应当越小越好。', '1');
INSERT INTO `panduan` VALUES (146, '电流表的内阻越小越好，而电压表的内阻越大越好。', '0');
INSERT INTO `panduan` VALUES (147, '测量直流时，仪表正极接线路负极、仪表负极接线路正极。', '1');
INSERT INTO `panduan` VALUES (148, '选用仪表时，应考虑仪表的准确度及仪表的量程，这样才能保证测量结果的准确性。', '0');
INSERT INTO `panduan` VALUES (149, '用指针式万用表的电阻档时，红表笔对应的是表内部电源的正极。', '1');
INSERT INTO `panduan` VALUES (150, '用指针式万用表测量桥式整流电路的输出电压时，黑表笔应接整流管的负极。', '0');
INSERT INTO `panduan` VALUES (151, '不使用万用表时，应将其波段开关置于直流电流最大档位。', '1');
INSERT INTO `panduan` VALUES (152, '钳形电流表是便携式电流表的一种，它的特点是可以在不切断电路的情况下测量流过电路的电流。', '0');
INSERT INTO `panduan` VALUES (153, '钳形电流表在测量过程中可以带电切换档位开关。', '1');
INSERT INTO `panduan` VALUES (154, '使用钳形电流表大量程测量小电流时，可将被测回路的导线在钳口中缠绕数圈，经计算后即可得出实测值。', '0');
INSERT INTO `panduan` VALUES (155, '用钳形电流表测量三相平衡负载电流时，钳口中放入两相导线时的指示值与放入一相导线时的指示值不同。', '1');
INSERT INTO `panduan` VALUES (156, '机械式兆欧表俗称“摇表”，是电气测量中最常用的便携式仪表。', '0');
INSERT INTO `panduan` VALUES (157, '兆欧表的有效指示范围应大于被测设备的绝缘电阻合格值', '0');
INSERT INTO `panduan` VALUES (158, '使用兆欧表之前应先调好机械零点。', '1');
INSERT INTO `panduan` VALUES (159, '兆欧表是用来测量绕组直流电阻的。', '1');
INSERT INTO `panduan` VALUES (160, '兆欧表在摇测电动机绝缘电阻时，可任意将L或E接至电动机的外壳。', '1');
INSERT INTO `panduan` VALUES (161, '用兆欧表测量电缆的绝缘电阻时，仪表G端应当空着。', '1');
INSERT INTO `panduan` VALUES (162, '用兆欧表测量电缆的绝缘电阻时，仪表G端的测试线应当接被测电缆线芯的绝缘。', '0');
INSERT INTO `panduan` VALUES (163, '测量有较大电容的电气设备的绝缘电阻时，读数和记录完毕后，应先拆开L端，后停止摇动，再进行放电。', '0');
INSERT INTO `panduan` VALUES (164, '接地电阻测量仪分三接线端子和四接线端子两种。', '0');
INSERT INTO `panduan` VALUES (165, '使用普通的兆欧表也可以测量接地电阻。', '1');
INSERT INTO `panduan` VALUES (166, '用接地电阻测量仪测量接地电阻时，电压极（P1）距被测接地体不得小于40m，电流极（C1）距被测接地体不得小于20m。', '1');
INSERT INTO `panduan` VALUES (167, '测量直流时，可使用磁电式、电磁式或电动式仪表。', '0');
INSERT INTO `panduan` VALUES (168, '测量交流时，也可使用磁电式、电动式等仪表。', '1');
INSERT INTO `panduan` VALUES (169, '测量电路的电压时，应将电压表串联在被测负载或电源电压的两端。', '1');
INSERT INTO `panduan` VALUES (170, '计量用的电度表，属于感应系仪表。', '0');
INSERT INTO `panduan` VALUES (171, '三相三线制电路中，可采用三相二元件有功功率表。', '0');
INSERT INTO `panduan` VALUES (172, '三相四线制电路中，也可采用三相二元件有功功率表。', '1');
INSERT INTO `panduan` VALUES (173, '应根据电力系统的相数和线数选择单相电能表、三相三线电能表或三相四线电能表。', '0');
INSERT INTO `panduan` VALUES (174, '电能表的额定电流应不小于被测电路的最大负荷电流。', '0');
INSERT INTO `panduan` VALUES (175, '如负载电流过大，可采用电流互感器扩大电能表的量程。', '0');
INSERT INTO `panduan` VALUES (176, '接入电流互感器二次回路的电流表，其线圈的额定电流均为5A。', '0');
INSERT INTO `panduan` VALUES (177, '用户电能表应当装接在用户电源开关的负荷侧。', '1');
INSERT INTO `panduan` VALUES (178, '智能电能表新增了计量信息管理、用电信息管理、电费记账、用电量监控等新功能。', '0');
INSERT INTO `panduan` VALUES (179, '基本安全用具的绝缘强度能长时间承受电气设备的工作电压。', '0');
INSERT INTO `panduan` VALUES (180, '辅助安全用具的绝缘强度不足以承受电气设备的工作电压，只能用于加强基本安全用具的作用。', '0');
INSERT INTO `panduan` VALUES (181, '绝缘鞋和绝缘靴都属于低压基本安全用具。', '1');
INSERT INTO `panduan` VALUES (182, '绝缘垫用厚度5mm以上，表面有防滑条纹的橡胶制成。其最小尺寸不宜小于0.8m×0.8m。', '0');
INSERT INTO `panduan` VALUES (183, '绝缘良好的绝缘垫属于基本安全用具。', '1');
INSERT INTO `panduan` VALUES (184, '绝缘站台最小尺寸不宜小于0.8m×0.8m.支持绝缘子高度不得小于10mm.', '1');
INSERT INTO `panduan` VALUES (185, '带绝缘柄的工具、绝缘手套、试电笔都属于低压基本安全用具。', '0');
INSERT INTO `panduan` VALUES (186, '绝缘靴在任何情况下都不能作为基本绝缘安全用具。', '0');
INSERT INTO `panduan` VALUES (187, '绝缘靴一般用作辅助安全用具，但可用作防护跨步电压的安全用具。', '0');
INSERT INTO `panduan` VALUES (188, '验电器分为高压验电器和低压验电器，用来检验导体是否带电以及判断某些带电特征。', '0');
INSERT INTO `panduan` VALUES (189, '高压验电器可用于低压验电，而低压验电器不能用于高压验电。', '1');
INSERT INTO `panduan` VALUES (190, '遮栏高度及其与带电体的距离应符合屏护的安全要求.', '0');
INSERT INTO `panduan` VALUES (191, '标示牌可用金属材料制成。', '1');
INSERT INTO `panduan` VALUES (192, '禁止合闸，有人工作！应挂在一经合闸即可送电到施工线路的线路开关和刀闸操作手柄上。', '0');
INSERT INTO `panduan` VALUES (193, '止步，高压危险！应挂在工作人员上下的铁架、梯子上。', '1');
INSERT INTO `panduan` VALUES (194, '梯子和高凳应坚固可靠，应能承受工作人员及其所携带工具的总重量。', '0');
INSERT INTO `panduan` VALUES (195, '安全腰带的宽度不应小于60mm。绕电杆带的单根拉力不应小于2206N。', '0');
INSERT INTO `panduan` VALUES (196, '在交流电路里，当验电器触及导线（或带电体）时，发亮的是相线，正常情况下，中性线也发亮。', '1');
INSERT INTO `panduan` VALUES (197, '用验电笔触及三相三线制星形接法的交流电路，有两根比通常稍亮，而另一根暗一些，说明较暗的相线有接地现象。', '0');
INSERT INTO `panduan` VALUES (198, '绝缘手套在电压1kV以下的电压区作业时，用作辅助安全用具；在对地电压250V以下电压区作业时，可作为基本安全用具。', '0');
INSERT INTO `panduan` VALUES (199, '在电气上用黄、绿、红三色分别代表L1、L2、L3三个相序。', '0');
INSERT INTO `panduan` VALUES (200, '安全标志一般设置在光线充足、醒目、稍高于视线的地方。', '0');
INSERT INTO `panduan` VALUES (201, '对于容易被人忽视的电气部位，如封闭的架线槽、设备上的电气盒，要用黑漆画上电气箭头。', '1');
INSERT INTO `panduan` VALUES (202, '电工钢丝钳手柄绝缘必须保持良好。', '0');
INSERT INTO `panduan` VALUES (203, '用电工钢丝钳剪断带电导线时，而应先剪断中性线，后剪断相线。', '1');
INSERT INTO `panduan` VALUES (204, '电工刀刀柄没有绝缘保护，不能在带电导线或器材上剖削。', '0');
INSERT INTO `panduan` VALUES (205, '活扳手不可反用，但可用钢管来接长手柄来加大的扳拧力矩。', '1');
INSERT INTO `panduan` VALUES (206, '长期未使用的冲击电钻和电锤，使用前应测量绝缘电阻。', '0');
INSERT INTO `panduan` VALUES (207, '冲击电钻和电锤的电源线必须是橡皮套软电缆。', '0');
INSERT INTO `panduan` VALUES (208, '手动导线压接钳也利用杠杆原理工作，多用于截面35mm2以上的导线接头的钳接管压接。', '1');
INSERT INTO `panduan` VALUES (209, '焊接较大截面的铜导线宜选用20－40W电烙铁。', '1');
INSERT INTO `panduan` VALUES (210, '电工防护用品包括防护眼镜、手套、安全帽等。', '0');
INSERT INTO `panduan` VALUES (211, '安全用具使用完毕后，应存放在干燥、通风的处所。安全用具应妥善保管。', '0');
INSERT INTO `panduan` VALUES (212, '安全用具应定期进行试验，定期试验合格后应加装标志。', '0');
INSERT INTO `panduan` VALUES (213, '0Ⅰ类设备的外壳上有接地端子。', '0');
INSERT INTO `panduan` VALUES (214, 'I类设备外壳内部没有接地端子。', '1');
INSERT INTO `panduan` VALUES (215, 'Ⅱ类是带有双重绝缘或加强绝缘的设备。', '0');
INSERT INTO `panduan` VALUES (216, 'Ⅲ类设备是由超低安全电压供电的设备。', '0');
INSERT INTO `panduan` VALUES (217, '市售手持电动工具绝大多数都是I类设备。', '1');
INSERT INTO `panduan` VALUES (218, 'Ⅱ类设备和Ⅲ类设备都无须采取接地或接保护线措施。', '0');
INSERT INTO `panduan` VALUES (219, '移动式电气设备的电源线必须采用绝缘良好的多股铜芯橡皮绝缘橡皮护套软电缆或铜芯聚氯乙烯绝缘聚氯乙烯护套软电缆。', '0');
INSERT INTO `panduan` VALUES (220, '移动式设备安装了两级漏电保护器即可免接PE线。', '1');
INSERT INTO `panduan` VALUES (221, '工地使用的移动式电气设备，应采用两级以上的漏电保护器。', '0');
INSERT INTO `panduan` VALUES (222, '在必须应用安全电压又没有安全隔离变压器的条件下，可以通过自耦变压器取得安全电压，并采取接地保护措施。', '1');
INSERT INTO `panduan` VALUES (223, '在使用手持电动工具及其他电气设备的过程中，如果遇到临时停电，应断开电源。', '0');
INSERT INTO `panduan` VALUES (224, '造成触电死亡事故的统计，几乎都是由Ⅲ类工具引起的。', '1');
INSERT INTO `panduan` VALUES (225, '如果使用Ⅰ类工具，必须装设额定漏电动作电流不大于30mA、动作时间不大于0.1s的剩余电流动作保护装置。', '0');
INSERT INTO `panduan` VALUES (226, '在狭窄场所如锅炉、金属容器，管道等应使用Ⅲ类工具。', '0');
INSERT INTO `panduan` VALUES (227, '带电部分与可触及导体之间的绝缘电阻Ⅰ类设备不低于2MΩ，Ⅱ类设备不低于7MΩ。', '0');
INSERT INTO `panduan` VALUES (228, '交流弧焊机的一次额定电压为380V，二次空载电压为70V左右，二次额定工作电压为30V左右。', '0');
INSERT INTO `panduan` VALUES (229, '交流弧焊机二次工作电流达数十至数百安，电弧温度高达1000℃。', '1');
INSERT INTO `panduan` VALUES (230, '安装前应检查弧焊机是否完好；绝缘电阻是否合格（一次绝缘电阻不应低于1MΩ、二次绝缘电阻不应低于0.5MΩ）。', '0');
INSERT INTO `panduan` VALUES (231, '弧焊机二次线长度一般不应超过50m。', '1');
INSERT INTO `panduan` VALUES (232, '为了防止运行中的弧焊机熄弧时70V左右的二次电压带来电击的危险，可以装设空载自动断电安全装置。', '0');
INSERT INTO `panduan` VALUES (233, '多台电焊机应尽量均匀的分接于三相电源，以尽量保持三相负荷平衡。', '0');
INSERT INTO `panduan` VALUES (234, '砂轮防护罩应牢固地安装在砂轮机头部相应的位置上，不得松动。', '0');
INSERT INTO `panduan` VALUES (235, '配电电器主要用于配电电路，对电路及设备进行通断以及保护、转换电源或负载的电器。', '0');
INSERT INTO `panduan` VALUES (236, '控制电器主要用于电力拖动和自动控制，控制受电设备，使其达到预期要求的工作状态的电器。', '0');
INSERT INTO `panduan` VALUES (237, '额定工作电压：在规定条件下保证电器正常工作的电压值。', '0');
INSERT INTO `panduan` VALUES (238, '额定电流：在规定条件下保证电器正常工作的电流值。', '0');
INSERT INTO `panduan` VALUES (239, '短路分断能力：在规定的条件下，包括开关电器出线端短路在内的极限分断能力。', '0');
INSERT INTO `panduan` VALUES (240, '开关应垂直安装。（非旋转操作机构的）在合闸状态时，操作手柄应向下。', '1');
INSERT INTO `panduan` VALUES (241, '低压隔离开关与低压断路器串联安装的线路中，送电时应先合上负荷侧隔离开关，再合上电源侧隔离开关，最后接通断路器。', '1');
INSERT INTO `panduan` VALUES (242, '低压隔离开关的主要作用是检修时实现电气设备与电源的隔离。', '0');
INSERT INTO `panduan` VALUES (243, '低压断路器只能有效地接通、断开负荷电流，而必须由熔断器断开短路电流。', '1');
INSERT INTO `panduan` VALUES (244, '装置式低压断路器有塑料外壳，也叫做塑料外壳式低压断路器。', '0');
INSERT INTO `panduan` VALUES (245, '一般额定电流在630A以下且短路电流不大时，可选用塑壳开关作为电路保护用。', '0');
INSERT INTO `panduan` VALUES (246, '低压断路器装有机械式自由脱扣机构。', '0');
INSERT INTO `panduan` VALUES (247, '大容量低压断路器闭合过程中，弧触头先闭合，主触头后闭合断开时顺序相反。', '0');
INSERT INTO `panduan` VALUES (248, '低压断路器的瞬时动作电磁式过电流脱扣器和热脱扣器都是起短路保护作用的。', '1');
INSERT INTO `panduan` VALUES (249, '低压断路器的瞬时动作电磁式过电流脱扣器的整定电流不得大于其额定电流。', '1');
INSERT INTO `panduan` VALUES (250, '低压断路器的瞬时动作电磁式过电流脱扣器是起过载保护作用的。', '1');
INSERT INTO `panduan` VALUES (251, '带有失压脱扣器的低压断路器，失压线圈断开后，断路器不能合闸。', '0');
INSERT INTO `panduan` VALUES (252, '低压断路器的分励脱扣器的作用是失压保护。', '1');
INSERT INTO `panduan` VALUES (253, '手动操作的塑料外壳式断路器故障掉闸后，恢复送电时必须将开关手柄向下扳至“再扣”位置后才能再次合闸送电。', '0');
INSERT INTO `panduan` VALUES (254, '智能化断路器可实现遥测、遥信、遥控。还可将故障数据保存，并依此可查出故障类型、故障电压、电流等。', '0');
INSERT INTO `panduan` VALUES (255, '断路器的分励脱扣器及失压脱扣器，在线路电压为额定值75％～110％时，应能可靠工作。', '0');
INSERT INTO `panduan` VALUES (256, '断路器的分励脱扣器及失压脱扣器，当电压低于额定值的35％时，失压脱扣器也应能可靠工作。', '1');
INSERT INTO `panduan` VALUES (257, '交流接触器适用于电气设备的频繁操作。', '0');
INSERT INTO `panduan` VALUES (258, '交流接触器能切断短路电流。', '1');
INSERT INTO `panduan` VALUES (259, '交流接触器吸引线圈的额定电压与接触器的额定电压总是一致的。', '1');
INSERT INTO `panduan` VALUES (260, '交流接触器铁芯上短路环的作用是过电压保护。', '1');
INSERT INTO `panduan` VALUES (261, '交流接触器多是利用灭弧栅进行灭弧的。', '0');
INSERT INTO `panduan` VALUES (262, '交流接触器的线圈既是吸持线圈又能起失压保护作用。', '0');
INSERT INTO `panduan` VALUES (263, '磁力起动器主要由交流接触器和热继电器组成。', '0');
INSERT INTO `panduan` VALUES (264, '磁力起动器本身能实现失压保护和过载保护。', '0');
INSERT INTO `panduan` VALUES (265, '行程开关是将机械信号转变为电信号的电器元件。', '0');
INSERT INTO `panduan` VALUES (266, '填料管式低压熔断器比纤维管式低压熔断器分断能力强。', '0');
INSERT INTO `panduan` VALUES (267, '熔断器具有良好的过载保护特性。', '1');
INSERT INTO `panduan` VALUES (268, '当负载电流达到熔断器熔体的额定电流时，熔体将立即熔断，从而起到过载保护的作用。', '1');
INSERT INTO `panduan` VALUES (269, '熔断器的熔断电流即其额定电流。', '1');
INSERT INTO `panduan` VALUES (270, '在正确安装和使用条件下，熔体为30A的熔断器，当负荷电流达到30A时，熔体在两个小时内应熔断。', '1');
INSERT INTO `panduan` VALUES (271, '安装普通RC系列插拔式熔断器的熔丝时，应将熔丝“盘圈”，盘圈方向应与螺钉（或螺母）紧固熔丝的方向相反。', '1');
INSERT INTO `panduan` VALUES (272, '热继电器只要按照负载额定电流选择整定值，就能起到短路保护的作用。', '1');
INSERT INTO `panduan` VALUES (273, '热继电器和热脱扣器的热容量较大，动作不快，不宜用于短路保护。', '0');
INSERT INTO `panduan` VALUES (274, '热元件的额定电流就是热继电器的额定电流。', '1');
INSERT INTO `panduan` VALUES (275, '热元件的额定电流应略大于负荷电流，一般在负荷电流的1.1～1.25倍之间。', '0');
INSERT INTO `panduan` VALUES (276, '热继电器动作后，一般在5min内实现自动复位。如手动复位，可在2min后按复位键完成。', '0');
INSERT INTO `panduan` VALUES (277, '中间继电器主要在电路中起信号传递与转换作用，用它可实现多路控制。', '0');
INSERT INTO `panduan` VALUES (278, 'Y－△起动器适用于任何接线方式的三相笼式异步电动机。', '1');
INSERT INTO `panduan` VALUES (279, '自耦减压起动器的优点之一是可以频繁操作。', '1');
INSERT INTO `panduan` VALUES (280, '软起动方式既改善了电动机起动时对电网的影响，又降低了电动机自身所承受的较大冲击力。', '0');
INSERT INTO `panduan` VALUES (281, '低压配电箱基本可分为固定式和手车式（抽屉式）两大类。', '0');
INSERT INTO `panduan` VALUES (282, '抽屉在推入小室以前，应检查断路器等处于分断状态。', '0');
INSERT INTO `panduan` VALUES (283, '抽屉拉出前应检查断路器等确已合上，方可将抽屉退到试验位置。', '1');
INSERT INTO `panduan` VALUES (284, '抽屉式配电箱应检查推抽是否灵活轻便，动、静触头应接触良好，并有足够的接触压力。', '0');
INSERT INTO `panduan` VALUES (285, '低压配电装置应定期进行清扫维护，一般每年不少于一次，且应安排在雷雨季节前和高峰负荷到来之前。', '1');
INSERT INTO `panduan` VALUES (286, '三相异步电动机主要由定子和转子两大部分组成。', '0');
INSERT INTO `panduan` VALUES (287, '三相异步电动机的电磁部分主要由铁心和绕组组成。', '0');
INSERT INTO `panduan` VALUES (288, '电动机的外壳防护等级第一位表征数字是对液体进入内部的防护。', '1');
INSERT INTO `panduan` VALUES (289, '三相异步电动机的定子铁心用硅钢片制作、转子铁心用铸钢制作。', '1');
INSERT INTO `panduan` VALUES (290, '所有三相异步电动机的转子绕组都是和定子绕组类似的三相绕组。', '1');
INSERT INTO `panduan` VALUES (291, '异步电动机的转子电流是由定子旋转磁场感应产生的。', '0');
INSERT INTO `panduan` VALUES (292, '电动机的额定功率是指电动机的输入功率。', '1');
INSERT INTO `panduan` VALUES (293, '异步电动机的同步转速与电动机的极数成正比。', '1');
INSERT INTO `panduan` VALUES (294, '异步电动机的额定转差率一般不小于20%。', '1');
INSERT INTO `panduan` VALUES (295, '异步电动机的电磁转矩与电源电压成正比。', '1');
INSERT INTO `panduan` VALUES (296, '电动机的额定功率是指额定运行条件下转轴上输出的机械功率。', '0');
INSERT INTO `panduan` VALUES (297, '三相异步电动机的额定电流是电动机额定运行时的线电流。', '0');
INSERT INTO `panduan` VALUES (298, '异步电动机的同步转速与磁极对数成反比。', '0');
INSERT INTO `panduan` VALUES (299, '异步电动机的同步转速即其额定转速。', '1');
INSERT INTO `panduan` VALUES (300, '异步电动机的同步转速即其旋转磁场的转速。', '0');
INSERT INTO `panduan` VALUES (301, '三相异步电动机的转子旋转方向与定子旋转磁场的旋转方向相同。', '0');
INSERT INTO `panduan` VALUES (302, '对于四极三相异步电动机，如其额定频率为50Hz，则其额定转速为1500r/min。', '1');
INSERT INTO `panduan` VALUES (303, '三相异步电动机的电流计算式只能用于星形接法的电动机。', '1');
INSERT INTO `panduan` VALUES (304, '三相异步电动机的电流计算式 只能用于三角形接法的电动机。', '1');
INSERT INTO `panduan` VALUES (305, '连续工作制的三相异步电动机满载运行时，运行的时间越长，其温升越高。', '1');
INSERT INTO `panduan` VALUES (306, '新投入运行的电动机，应空载运行一段时间。', '0');
INSERT INTO `panduan` VALUES (307, '三相异步电动机在空载或轻载运行时，其功率因数低于铭牌所示的数值。', '0');
INSERT INTO `panduan` VALUES (308, '电动机采用熔丝保护，当其运行电流达到熔丝额定电流时，熔丝将会熔断。', '1');
INSERT INTO `panduan` VALUES (309, 'B级绝缘的最热点温度为130℃， B级绝缘的Y系列异步电动机运行时外壳温度不得超过130℃。', '1');
INSERT INTO `panduan` VALUES (310, '能耗制动是在制动转矩的作用下，电动机将迅速停车。', '0');
INSERT INTO `panduan` VALUES (311, '将三相电动机的电源任意调换两相，即可改变旋转磁场的方向，实现电动机反转。', '0');
INSERT INTO `panduan` VALUES (312, '要想改变三相异步电动机的旋转方向，只要改变进入定子绕组三相电流的相序即可。', '0');
INSERT INTO `panduan` VALUES (313, '将三相异步电动机的相序由A—B—C改为C—A—B，即可改变其旋转方向。', '1');
INSERT INTO `panduan` VALUES (314, '改变电流的频率不能改变电动机的转速。', '1');
INSERT INTO `panduan` VALUES (315, '运行中的三相电动机缺一相时，运行时间过长就有烧毁电动机的可能。', '0');
INSERT INTO `panduan` VALUES (316, '（Y─△）起动，使加在每相绕组上的电压降至额定电压的 ，因而起动电流就可减小到直接起动时的1/3。', '0');
INSERT INTO `panduan` VALUES (317, '自耦变压器备有不同的电压抽头，如80％、65％的额定电压，以供根据负载转矩大小选择不同的起动电压。', '0');
INSERT INTO `panduan` VALUES (318, '电动机通常应具有短路、过载及失压保护措施。', '0');
INSERT INTO `panduan` VALUES (319, '运行中的电动机三相电压不平衡度一般不应大于线间电压的5％，三相电流不平衡度不应大于10％。', '0');
INSERT INTO `panduan` VALUES (320, '在电动机输出力不变的情况下，一般电源电压允许变化范围为+10％～-5％。', '0');
INSERT INTO `panduan` VALUES (321, '单相异步电动机定子绕组接通交流电源后也会产生旋转磁场。', '0');
INSERT INTO `panduan` VALUES (322, '所有单相电容电动机的两组绕组都是始终接通电源的。', '1');
INSERT INTO `panduan` VALUES (323, '单相串励电动机是一种交、直流两用的电动机。', '0');
INSERT INTO `panduan` VALUES (324, '并联电容器的主要作用之一是用来补偿滞后的无功功率。', '0');
INSERT INTO `panduan` VALUES (325, '安装并联电容器组可以提高负载的功率因数。', '1');
INSERT INTO `panduan` VALUES (326, '集中补偿，这种补偿方式是将电力电容器安装在变配电所内。', '0');
INSERT INTO `panduan` VALUES (327, '电容器内部一般内装自放电电阻和保险装置的。要求在电容器退出运行后，应在3～10min内将残余的电荷降至75V以下。', '0');
INSERT INTO `panduan` VALUES (328, '低压三相并联电容器内部是三角形连接的。', '0');
INSERT INTO `panduan` VALUES (329, '因为并联电容器既能提高线路上的功率因数，又能改善电压质量，所以接入线路的并联电容器越多越好。', '1');
INSERT INTO `panduan` VALUES (330, '并联电容器应避免阳光直射，受阳光直射的窗玻璃应涂以白色。', '0');
INSERT INTO `panduan` VALUES (331, '液体介质为矿物油的并联电容器是有爆炸危险的电气设备。', '0');
INSERT INTO `panduan` VALUES (332, '并联电容器投入或退出的主要依据是功率因数的高低。', '0');
INSERT INTO `panduan` VALUES (333, '当功率因数低于0.9电压偏低时应退出电容器组。', '1');
INSERT INTO `panduan` VALUES (334, '并联电容器运行中电流和电压不应长时间超过并联电容器额定电流和额定电压的1.3倍。', '1');
INSERT INTO `panduan` VALUES (335, '保护单台并联电容器的熔断器，其熔丝额定电流按并联电容器额定电流的1.5～2.5倍选用。', '0');
INSERT INTO `panduan` VALUES (336, '并联电容器的放电装置应能保证10min内将电容器两端的电压从峰值降至安全范围内。', '0');
INSERT INTO `panduan` VALUES (337, '并联电容器组放电装置的电阻越大，则放电时间越长，残留电压的下降也越慢。', '0');
INSERT INTO `panduan` VALUES (338, '并联电容器刚退出运行后，必须在1min以后才允许再次投入运行。', '1');
INSERT INTO `panduan` VALUES (339, '正常情况下全站恢复送电时，应先合上并联电容器组开关，后合上各出线开关。', '1');
INSERT INTO `panduan` VALUES (340, '控制并联电容器的断路器跳闸后，在未查明故障原因且未将故障消除之前，不得强送电。', '0');
INSERT INTO `panduan` VALUES (341, '并联电容器断开电源后，工作人员接近之前，不论该并联电容器是否装有放电装置，都必须进行人工放电。', '0');
INSERT INTO `panduan` VALUES (342, '应用兆欧表测量并联电容器的绝缘电阻是测量并联电容器相间绝缘电阻。', '1');
INSERT INTO `panduan` VALUES (343, '电容器外壳和钢架均应采取接PE线措施。', '0');
INSERT INTO `panduan` VALUES (344, '当功率因数高于0.95且有超前趋势、电压偏高时应退出电容器组。', '0');
INSERT INTO `panduan` VALUES (345, '工作照明是保证在工作时生产视觉条件的各种照明。', '0');
INSERT INTO `panduan` VALUES (346, '事故照明是因正常照明的电源失效而启用的照明，包括疏散照明、安全照明、备用照明。', '0');
INSERT INTO `panduan` VALUES (347, '在三相四线制配电系统中，其照明负荷应尽可能均匀地分布在三相中。', '0');
INSERT INTO `panduan` VALUES (348, '以气体放电灯为主要负荷的电路中，中性线截面可小于相线截面。', '1');
INSERT INTO `panduan` VALUES (349, '应急照明线路不能与动力线路合用，允许与工作照明线路合用。', '1');
INSERT INTO `panduan` VALUES (350, '应急照明必须有自己的供电线路。', '0');
INSERT INTO `panduan` VALUES (351, '额定电压为220V的白炽灯，如果电源电压降低10%，其电功率也将下降10%。。', '1');
INSERT INTO `panduan` VALUES (352, '白炽灯只消耗有功功率。', '0');
INSERT INTO `panduan` VALUES (353, '小于400W的高压水银灯、高压钠灯的导线截面不小于1.5 mm2', '0');
INSERT INTO `panduan` VALUES (354, '大于400W，小于1000W高压水银灯，导线截面不小于1.5mm2。', '1');
INSERT INTO `panduan` VALUES (355, '照明线路允许电压损失，规定为额定电压的5％～10％。', '0');
INSERT INTO `panduan` VALUES (356, '室内照明支线，每一个单相回路，灯具和插座的数量不得超过30个，断路器过流脱扣电流值不应大于15A。', '1');
INSERT INTO `panduan` VALUES (357, '照明配电箱宜设置在靠近照明负荷中心便于操作维护的位置。', '0');
INSERT INTO `panduan` VALUES (358, '灯具重量大于0.5kg的灯具应采用吊链、吊管吊装，灯线不得受力。', '0');
INSERT INTO `panduan` VALUES (359, '一般敞开式灯具，灯头距地一般规定为室内不低于2.5m、室外也不低于2.5m。', '1');
INSERT INTO `panduan` VALUES (360, '照明灯具的单极开关不得接在地线上，而必须接到中性线上。', '1');
INSERT INTO `panduan` VALUES (361, '螺口灯座的顶芯接相线L或中性线N均可以。', '1');
INSERT INTO `panduan` VALUES (362, '翘板开关距地面高度1m，其边缘距门框边缘的距离0.15～0.2m。', '1');
INSERT INTO `panduan` VALUES (363, '照明开关位置应与灯具的位置相对应。', '0');
INSERT INTO `panduan` VALUES (364, '不同电压的插座应有明显的区别，不能互用。', '0');
INSERT INTO `panduan` VALUES (365, '明装插座距地面不应低于1.8m，暗装插座距地面不应低于1.3m。', '1');
INSERT INTO `panduan` VALUES (366, '单相三孔插座的保护线应接在插孔下方的接线端子上。', '1');
INSERT INTO `panduan` VALUES (367, '住宅用户配电箱内单相照明线路的开关采用双极开关或单极开关。', '1');
INSERT INTO `panduan` VALUES (368, '同样瓦数的荧光灯和白炽灯，荧光灯比白炽灯省电。', '1');
INSERT INTO `panduan` VALUES (369, '移动式电气设备的动力回路与照明回路，应由两个支路开关分别控制。', '0');
INSERT INTO `panduan` VALUES (370, '电杆埋设深度应符合设计要求，一般情况可取杆长的1/10+0.7m，但最浅不少于1.5m。变台电杆不应少于2m。', '0');
INSERT INTO `panduan` VALUES (371, '上层横担至杆顶距离，直线杆一般不小于200mm。', '1');
INSERT INTO `panduan` VALUES (372, '同杆架设的回路数。380/220V线路时，不应超过5个回路。', '1');
INSERT INTO `panduan` VALUES (373, '耐张杆应能承受在断线情况下沿线路方向导线的拉力。', '0');
INSERT INTO `panduan` VALUES (374, '有保护线在同一横担架设时，面向负荷从左至右为：L1、N、L2、L3、PE。', '0');
INSERT INTO `panduan` VALUES (375, '在城市及居民区，低压架空线路电杆的档距一般不应超过50m。', '0');
INSERT INTO `panduan` VALUES (376, '架空线的弧垂越小越好。', '1');
INSERT INTO `panduan` VALUES (377, '当架空线对地高度不够时，可以采取紧线的办法来提高导线高度。', '1');
INSERT INTO `panduan` VALUES (378, '架空线路不允许采用单股铝线及铝合金线，铝绞线、钢心铝绞线最小截面为25mm2。', '0');
INSERT INTO `panduan` VALUES (379, '架空线路同一档距内，同一根导线上只允许有一个接头。', '0');
INSERT INTO `panduan` VALUES (380, '高压线路与低压线路同杆架设时，档距应符合低压线路的要求。', '0');
INSERT INTO `panduan` VALUES (381, '架空线路跨越易燃材料制作屋顶的建筑物时，其间垂直距离不得小于2.5m。', '1');
INSERT INTO `panduan` VALUES (382, '对于架空线路，只要求白天进行，不要求夜间巡视。', '1');
INSERT INTO `panduan` VALUES (383, '1. 380V/220V配电线路电杆引至用电单位第一支持物的一段线路，称为低压接户线。', '0');
INSERT INTO `panduan` VALUES (384, '接户线档距不宜超过25m，否则应加装接户杆。', '0');
INSERT INTO `panduan` VALUES (385, '接户线档距内只允许有一个接头。', '1');
INSERT INTO `panduan` VALUES (386, '低压接户线应采用绝缘导线，铜、铝导线均可。', '0');
INSERT INTO `panduan` VALUES (387, '1. 普通拉线与地面的夹角不应小于60°。', '1');
INSERT INTO `panduan` VALUES (388, '电缆直埋深度：一般不小于0.7m，沟底深应为0.8m。', '0');
INSERT INTO `panduan` VALUES (389, '电缆敷设中应保持规定的弯曲半径，以防止损伤电缆的绝缘。', '0');
INSERT INTO `panduan` VALUES (390, '室内电缆终端头，每1～3年停电检修一次。', '0');
INSERT INTO `panduan` VALUES (391, '直埋地下的电力电缆受温度变化的影响小，比相同材质、相同截面的架空线路导线的安全载流量大。', '1');
INSERT INTO `panduan` VALUES (392, '当没有四芯电缆时，可采用带金属铠装或金属护套的三芯电缆外加一根导线的敷设方式。', '1');
INSERT INTO `panduan` VALUES (393, '室内配线应选择绝缘导线，有阻燃要求的，应选择绝缘阻燃导线。', '0');
INSERT INTO `panduan` VALUES (394, '各种明配线装置的水平高度距地面不应低于2.5m，垂直敷设不应低于1.8m', '0');
INSERT INTO `panduan` VALUES (395, '重要的档案室、资料室、仓库和集会场所，易燃易爆场所，剧场舞台的照明，木槽板配线，剧烈振动的场所，严禁使用铝线配线。', '0');
INSERT INTO `panduan` VALUES (396, '护套线明敷配线用于环境温度20～40℃之间，清洁、干燥、无腐蚀性气体、装饰要求不高的室内。', '0');
INSERT INTO `panduan` VALUES (397, '护套线弯曲，弯曲半径不小于护套线外径4倍。', '0');
INSERT INTO `panduan` VALUES (398, '槽板规格应与导线规格和根数相适应，一般规定导线（含绝缘层）的总截面积不大于槽板内径1/4。', '1');
INSERT INTO `panduan` VALUES (399, '采用钢管明管配线时，钢管壁厚不应小于1.0mm。', '0');
INSERT INTO `panduan` VALUES (400, '埋在混凝土内的暗管，采用普通钢管时管壁厚不应小于1.0mm，应做防腐处理。', '1');
INSERT INTO `panduan` VALUES (401, '多根导线穿管时，管内导线总截面（含绝缘层）不应超过导线管内净截面的40%。', '0');
INSERT INTO `panduan` VALUES (402, '管子的弯曲半径不小于管外径的2倍。', '1');
INSERT INTO `panduan` VALUES (403, '管长度每超过20m有一个弯曲，应设置接线盒或拉线盒。', '0');
INSERT INTO `panduan` VALUES (404, '管子与其他管线平行为0.1m，交叉为0.05m。', '0');
INSERT INTO `panduan` VALUES (405, '穿管的绝缘导线，铜线容许最小截面为1mm2、铝线容许最小截面为2.5mm2。', '0');
INSERT INTO `panduan` VALUES (406, '每一电线管内只允许有1个电线接头。', '1');
INSERT INTO `panduan` VALUES (407, '临时用电工程、设施和设备应设立时间，超过一年以上应按正式和正式用电规定安装。', '1');
INSERT INTO `panduan` VALUES (408, '临时用电应不必考虑用电负荷容量与供电电源容量是否相适应。', '1');
INSERT INTO `panduan` VALUES (409, '用电设备必须采用一机一闸，一箱一漏，开关箱中必须装设剩余电流保护器。', '0');
INSERT INTO `panduan` VALUES (410, '架空线路与施工建筑物的水平距离一般不得小于10m。', '0');
INSERT INTO `panduan` VALUES (411, '架空线路与地面的垂直距离不得小于5m。', '1');
INSERT INTO `panduan` VALUES (412, '架空线路跨越建筑物时与其顶部的垂直距离不得小于2.5m。', '0');
INSERT INTO `panduan` VALUES (413, '塔式起重机附近的架空线路，应在臂杆回转半径及被吊物1.m以外', '1');
INSERT INTO `panduan` VALUES (414, '各种配电线路禁止敷设在树上、脚手架上，但可放在地面上。', '1');
INSERT INTO `panduan` VALUES (415, '配电线路每一支路的始端必须装设断路开关和有效的短路保护及过载保护。', '0');
INSERT INTO `panduan` VALUES (416, '暂时停用的线路应及时切断电源；工程竣工后，配电线路可暂时不拆除。', '1');
INSERT INTO `panduan` VALUES (417, '电气设备的接地线或接保护线应使用多股铜线，禁止使用铝线。', '0');
INSERT INTO `panduan` VALUES (418, '施工现场及临时生活区高度在20m及以上高大建筑，应装设防雷保护装置，并及时用导线与建筑物接地线连接。', '0');
INSERT INTO `panduan` VALUES (419, '塔式起重机的轨道，一般应设两组接地装置；对塔线较长的轨道，每隔30m应补做一组接地装置。', '1');
INSERT INTO `panduan` VALUES (420, '配电箱内必须装设中性线端子板和保护端子板。', '0');
INSERT INTO `panduan` VALUES (421, '配电箱、盘的操作面上的操作部位不得有带电体明露。', '0');
INSERT INTO `panduan` VALUES (422, '具有三个及以上回路的配电箱、盘应装设总开关，各分路开关均应标有回路名称。', '0');
INSERT INTO `panduan` VALUES (423, '光力合一的流动配电箱，一般应装设三极剩余电流动作保护开关或防中性线断线的安全保护装置。', '1');
INSERT INTO `panduan` VALUES (424, '用电设备至配电箱之间的距离，一般不应大于10m。', '1');
INSERT INTO `panduan` VALUES (425, '固定式配电箱至流动闸箱之间的距离，最大不应超过40m。', '0');
INSERT INTO `panduan` VALUES (426, '施工现场消防泵房的电源，必须引自变压器二次总闸或现场电源总闸的外侧，其电源线宜采用暗敷设。', '0');
INSERT INTO `panduan` VALUES (427, '办公室、宿舍的灯，每盏应设开关控制。', '0');
INSERT INTO `panduan` VALUES (428, '灯头与易燃烧物的净具一般不小于300mm。', '0');
INSERT INTO `panduan` VALUES (429, '聚光灯、碘钨灯等高热灯具与易燃物应保持安全距离，一般不小于400mm。', '1');
INSERT INTO `panduan` VALUES (430, '局部照明灯、行灯及标灯，供电电压不应超过36V。', '0');
INSERT INTO `panduan` VALUES (431, '行灯电源线应使用绝缘护套线或橡皮套缆线，也可使用塑料护套软线。', '1');
INSERT INTO `panduan` VALUES (432, '钢索配线间距不大于12m，护套线配线允许直接敷设于钢索上。', '0');
INSERT INTO `panduan` VALUES (433, '闪电放电时在附近导体上产生的闪电静电感应和闪电电磁感应，它可能使金属部件之间产生火花放电。', '0');
INSERT INTO `panduan` VALUES (434, '直击雷和闪电感应都能在架空线路、电缆线路或金属管道上产生沿线路或管道的两个方向迅速传播的闪电电涌（又称雷电波）侵入。', '0');
INSERT INTO `panduan` VALUES (435, '雷电冲击波具有低频特征。', '1');
INSERT INTO `panduan` VALUES (436, '用于防直击雷的防雷装置，由接闪器、引下线和接地装置组成。', '0');
INSERT INTO `panduan` VALUES (437, '防直击雷的人工接地体距建筑物出入口和人行道不应小于3m。', '0');
INSERT INTO `panduan` VALUES (438, '独立接闪杆的接地装置与接地网的地中距离不应小于2m。', '1');
INSERT INTO `panduan` VALUES (439, '雷电侵入波造成的事故很多。在低压系统，这种事故占总事故的70%以上。', '0');
INSERT INTO `panduan` VALUES (440, '避雷针是防止雷电波侵入的防雷装置。', '1');
INSERT INTO `panduan` VALUES (441, '装设独立避雷针以后就可以避免发生雷击。', '1');
INSERT INTO `panduan` VALUES (442, '独立避雷针的接地装置必须与其他接地装置分开。', '0');
INSERT INTO `panduan` VALUES (443, '阀型避雷器是防止雷电波侵入的防雷装置。', '0');
INSERT INTO `panduan` VALUES (444, '避雷器是用来防护雷电产生的过电压沿线路侵入变配电所或建筑物内，以免危及被保护设备的绝缘。', '0');
INSERT INTO `panduan` VALUES (445, '避雷器的型式主要有阀型避雷器和氧化锌避雷器，目前应用较多的是氧化锌避雷器。', '0');
INSERT INTO `panduan` VALUES (446, '当采用架空线供电时，在进户处装设一组低压阀型避雷器并与绝缘子铁脚、金具连在一起接到电气设备的接地装置上等。', '0');
INSERT INTO `panduan` VALUES (447, '为了防止直击雷伤人，雷雨天气尽量避免在野外逗留。', '0');
INSERT INTO `panduan` VALUES (448, '为了防止直击雷伤人，应尽量靠近山丘、海滨、河边、池旁。', '1');
INSERT INTO `panduan` VALUES (449, '为了防止直击雷伤人，可以用金属杆的雨伞，可把带有金属杆的工具如铁锹、锄头扛在肩上。', '1');
INSERT INTO `panduan` VALUES (450, '为了防止雷电伤人，应远离各种天线、电线杆、高塔、烟囱、旗杆、孤独的树木和没有防雷装置的孤立小建筑等。', '0');
INSERT INTO `panduan` VALUES (451, '静电现象是一种常见的带电现象，如电容器残留电荷、摩擦带电等。', '0');
INSERT INTO `panduan` VALUES (452, '产生静电电荷的多少与生产物料的性质和料量、摩擦力大小和摩擦长度、液体和气体的分离或喷射强度、粉体粒度等因素无关。', '1');
INSERT INTO `panduan` VALUES (453, '静电电量虽然不大，但因其电压很高而容易发生放电，产生静电火花，引起爆炸或火灾。', '0');
INSERT INTO `panduan` VALUES (454, '接地是采取接地、增湿、加入抗静电添加剂等措施使静电电荷比较容易泄漏、消散，以避免静电的积累，是消除静电危害最简单的方法。', '0');
INSERT INTO `panduan` VALUES (455, '静电接地装置应当连接牢靠，并有足够的机械强度，可以同其它目的接地用一套接地装置。', '0');
INSERT INTO `panduan` VALUES (456, '良好的绝缘也是保证电气系统正常运行的基本条件。', '0');
INSERT INTO `panduan` VALUES (457, '绝缘材料一般分为：气体绝缘。液体绝缘。固体绝缘。', '0');
INSERT INTO `panduan` VALUES (458, 'B级绝缘的允许工作温度为150℃。', '1');
INSERT INTO `panduan` VALUES (459, '气体击穿后绝缘性能很快得到恢复。', '0');
INSERT INTO `panduan` VALUES (460, '固体绝缘击穿后需要经过较长时间才能恢复其原有绝缘性能。', '1');
INSERT INTO `panduan` VALUES (461, '新装和大修后的低压电力布线和配电装置，要求绝缘电阻不低于0.5MΩ。', '0');
INSERT INTO `panduan` VALUES (462, '携带式电气设备的绝缘电阻不应低于1MΩ。', '1');
INSERT INTO `panduan` VALUES (463, '屏护和间距是最为常用的电气安全措施之一。', '0');
INSERT INTO `panduan` VALUES (464, '对于低压设备，遮栏与裸导体之间的距离不应小于0.8m。', '0');
INSERT INTO `panduan` VALUES (465, '低压线路与10kV高压线路之间不得小于1.2m。', '0');
INSERT INTO `panduan` VALUES (466, '低压接户线跨越通车街道时，对地距离不应小于6m。', '0');
INSERT INTO `panduan` VALUES (467, '跨越通车困难的街道或人行道时，不应小于3m。', '1');
INSERT INTO `panduan` VALUES (468, '低压配电装置正面通道的宽度，单列布置时不应小于1.5m；双列布置时不应小于2m。', '0');
INSERT INTO `panduan` VALUES (469, '通道上方裸导电部分的高度不应低于2m。', '1');
INSERT INTO `panduan` VALUES (470, '室内吊灯灯具高度一般应大于2.5m；受条件限制时可减为2m。', '1');
INSERT INTO `panduan` VALUES (471, '在低压工作中，人体或其所携带工具与带电体的距离不应小于0.1m。', '0');
INSERT INTO `panduan` VALUES (472, '双重绝缘指工作绝缘（基本绝缘）和保护绝缘（附加绝缘）。', '0');
INSERT INTO `panduan` VALUES (473, '工作绝缘的绝缘电阻不得低于2MΩ。', '0');
INSERT INTO `panduan` VALUES (474, '保护绝缘的绝缘电阻不得低于5MΩ、加强绝缘的绝缘电阻也不得低于5MΩ。', '1');
INSERT INTO `panduan` VALUES (475, 'Ⅱ类设备在其明显部位应有“回”形标志。', '0');
INSERT INTO `panduan` VALUES (476, '一般场所使用的手持电动工具应优先选用Ⅱ类设备。', '0');
INSERT INTO `panduan` VALUES (477, 'Ⅱ类设备必须采取接地、接零安全措施。', '1');
INSERT INTO `panduan` VALUES (478, '凡属双重绝缘的设备，不得再行接地或接保护线。', '0');
INSERT INTO `panduan` VALUES (479, '凡特别危险环境使用的手持式电动工具应采用42V特低电压。', '0');
INSERT INTO `panduan` VALUES (480, '凡有电击危险环境使用的手持照明灯和局部照明灯应采用36V或24V特低电压。', '0');
INSERT INTO `panduan` VALUES (481, '金属容器内、隧道内、水井内以及周围有大面积接地导体等工作地点狭窄、行动不便的环境应采用12V特低电压。', '0');
INSERT INTO `panduan` VALUES (482, '供给安全电压的变压器的一次边与二次边之间不得有电气连接。', '0');
INSERT INTO `panduan` VALUES (483, '局部照明变压器应采用双绕组变压器，并且一次侧、二次侧分别装有短路保护元件。', '0');
INSERT INTO `panduan` VALUES (484, '因为36V是安全电压，所以在任何情况下，人体触及该电路都不致遇到危险。', '1');
INSERT INTO `panduan` VALUES (485, '安全电压回路的带电部分必须与较高电压的回路保持电气隔离。', '0');
INSERT INTO `panduan` VALUES (486, '安全电压的插座应该带有接零或接地插头或插孔。', '1');
INSERT INTO `panduan` VALUES (487, '剩余电流动作保护装置（又称“漏电保护器”）的主要功能是提供间接接触电击保护。', '0');
INSERT INTO `panduan` VALUES (488, '市售产品大多数都是电子式电流型剩余电流动作保护器。', '0');
INSERT INTO `panduan` VALUES (489, '剩余电流动作保护装置采用零序电流互感器作为取得触电或漏电电流信号的检测元件。', '0');
INSERT INTO `panduan` VALUES (490, '安装剩余电流动作保护装置时，被保护设备的外壳没有接地或接PE保护也能起到保护作用。', '1');
INSERT INTO `panduan` VALUES (491, '300mA及以下的属高灵敏度，主要用于防止触电事故。', '1');
INSERT INTO `panduan` VALUES (492, '为了避免误动作，保护装置的额定不动作电流不得低于额定动作电流的1/3。', '1');
INSERT INTO `panduan` VALUES (493, '动力与照明合用的三相四线制线路必须选用四极保护器。', '0');
INSERT INTO `panduan` VALUES (494, '剩余电流动作保护开关的额定电压、额定电流、分断能力等均应与线路条件适应。', '0');
INSERT INTO `panduan` VALUES (495, '工作零线和保护零线都应当穿过漏电保护器。', '1');
INSERT INTO `panduan` VALUES (496, '对使用中的剩余电流动作保护装置应定期用试验按钮检查其动作特性是否正常。', '0');
INSERT INTO `panduan` VALUES (497, '漏电保护器试验按钮允许频繁操作。', '1');
INSERT INTO `panduan` VALUES (498, '《中华人民共和国安全生产法》规定，生产经营单位应当对从业人员进行安全生产教育和培训，保证从业人员具备必要的安全生产知识，熟悉有关的安全生产规章制度和安全操作规程，掌握本岗位的安全操作技能，了解事故应急处理措施，知悉自身在安全生产方面的权利和义务。未经安全生产教育和培训合格的从业人员，不得上岗作业。', '0');
INSERT INTO `panduan` VALUES (499, '《中华人民共和国安全生产法》规定，负有安全生产监督管理职责的部门依法对存在隐患的生产经营单位作出停产停业、停止施工、停止使用相关设施或者设备的决定，生产经营单位应当依法执行，及时消除事故隐患。', '1');
INSERT INTO `panduan` VALUES (500, '《中华人民共和国安全生产法》规定，从业人员应当接受安全生产教育和培训，掌握本职工作所需的安全生产知识。', '0');
INSERT INTO `panduan` VALUES (501, '《中华人民共和国安全生产法》规定，从业人员应当遵守本单位的安全生产规章制度和操作规程，服从管理，正确佩戴和使用劳动防护用品。', '0');
INSERT INTO `panduan` VALUES (502, '《中华人民共和国安全生产法》规定，危险物品是指易燃易爆物品、危险化学品、放射性物品、有毒物品等能够危及人身安全和财产安全的物品。', '1');
INSERT INTO `panduan` VALUES (503, '《中华人民共和国安全生产法》规定，任何单位和个人不得阻挠和干涉对事故的依法调查处理。', '0');
INSERT INTO `panduan` VALUES (504, '《中华人民共和国安全生产法》规定，生产经营单位的从业人员有依法获得安全生产保障的权利，并应当依法履行安全生产方面的义务。', '0');
INSERT INTO `panduan` VALUES (505, '《中华人民共和国安全生产法》规定，任何单位或者个人对事故隐患或者安全生产违法行为，均有权向负有安全生产监督管理职责的部门报告或者举报。', '0');
INSERT INTO `panduan` VALUES (506, '《中华人民共和国安全生产法》规定，生产经营单位与从业人员订立协议，免除或者减轻其对从业人员因生产安全事故伤亡依法应承担的责任的，该协议无效；对生产经营单位的主要负责人、个人经营的投资人处五万元以上十万元以下的罚款。', '1');
INSERT INTO `panduan` VALUES (507, '《中华人民共和国安全生产法》规定，国家实行生产安全事故责任追究制度，依照本法和有关法律、法规的规定，追究生产安全事故责任单位和责任人员的法律责任。', '0');
INSERT INTO `panduan` VALUES (508, '《中华人民共和国安全生产法》规定，从业人员发现危及人身安全的紧急时，无权停止作业或者在采取可能的应急措施后撤离作业场所。', '1');
INSERT INTO `panduan` VALUES (509, '《中华人民共和国安全生产法》规定，生产经营单位必须依法参加工伤保险，为从业人员缴纳保险费。', '0');
INSERT INTO `panduan` VALUES (510, '《中华人民共和国安全生产法》规定，生产经营单位必须为从业人员提供符合国家标准或者行业标准的劳动防护用品，并监督、教育从业人员按照使用规则佩戴、使用。', '0');
INSERT INTO `panduan` VALUES (511, '《中华人民共和国安全生产法》规定，生产经营单位必须执行依法制定的保障安全生产的国家标准或者地方标准。', '1');
INSERT INTO `panduan` VALUES (512, '《中华人民共和国安全生产法》规定，未经安全生产教育和培训合格的从业人员，不得上岗作业。', '0');
INSERT INTO `panduan` VALUES (513, '《中华人民共和国安全生产法》规定，因生产安全事故受到损害的从业人员，除依法享有工伤保险外，依照有关民事法律尚有获得赔偿的权利的，有权提出赔偿要求。', '0');
INSERT INTO `panduan` VALUES (514, '《北京市安全生产条例》规定，在经营场所设置标志明显的安全出口和符合疏散要求的疏散通道，并确保畅通。', '0');
INSERT INTO `panduan` VALUES (515, '《北京市安全生产条例》规定，生产经营单位对存在较大危险因素的设备、设施应当设置明显的安全警示标志。', '0');
INSERT INTO `panduan` VALUES (516, '《北京市安全生产条例》规定，生产安全事故案例是安全生产的教育和培训主要内容之一。', '0');

-- ----------------------------
-- Table structure for xuanze
-- ----------------------------
DROP TABLE IF EXISTS `xuanze`;
CREATE TABLE `xuanze`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `a` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `b` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `c` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `d` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 403 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of xuanze
-- ----------------------------
INSERT INTO `xuanze` VALUES (1, '电工是特殊工种，也是危险工种。首先，其作业过程和工作质量不但关联着自身安全，而且关联着（）和周围设施的安全', '他人', '线路', '电缆', '配电室');
INSERT INTO `xuanze` VALUES (2, '电工作业人员对配电设备设施应定期进行（ ）巡视检查，认真做好各项运行管理记录，包括设备巡视检查记录、设备检修记录、工具检测记录、运行分析记录、值班记录等。', '全面', '电流互感器', '变压器', '断路器');
INSERT INTO `xuanze` VALUES (3, '在停电的低压动力和照明回路上工作可不填写工作票。但在不停电的线路上进行接户线工作时应填写第二种工作票，并有人（）。', '监护', '帮助', '监督', '检查');
INSERT INTO `xuanze` VALUES (4, '在雷电、雨、雪、大雾及（）级以上大风等气候条件下，一般不应进行室外带电作业。', '五', '四', '三', '六');
INSERT INTO `xuanze` VALUES (5, '电压的单位符号是( )。', 'V', 'kW', 'J', 'A');
INSERT INTO `xuanze` VALUES (6, '电流的单位符号是( )。', 'A', 'W', 'F', 'mV');
INSERT INTO `xuanze` VALUES (7, '电位的单位符号是( )。', 'V', 'A', 'W', '%');
INSERT INTO `xuanze` VALUES (8, '电动势的单位符号是( )。', 'V', 'A', 'C', 'kW');
INSERT INTO `xuanze` VALUES (9, '部分电路欧姆定律的表达式是( )。', 'Ｉ=U/R', 'U=Ｉ/R', 'R=UＩ', 'Ｉ=UR');
INSERT INTO `xuanze` VALUES (10, '全电路欧姆定律的表达式是( )。', 'Ｉ＝Ｅ／Ｒ＋Ｒ0', 'Ｕ＝ＩＲ0', 'Ｕ＝Ｅ＋ＩＲ0', 'Ｉ＝（Ｕ－Ｅ）／Ｒ0');
INSERT INTO `xuanze` VALUES (11, '串联电路的总阻抗与各分阻抗的关系是( )。', '总阻抗>分阻抗', '总阻抗<分阻抗', '总阻抗=分阻抗', '无关');
INSERT INTO `xuanze` VALUES (12, '并联电路的总阻抗与各分阻抗的关系是( )。', '总阻抗<分阻抗', '总阻抗=分阻抗', '总阻抗>分阻抗', '无关');
INSERT INTO `xuanze` VALUES (13, '串联电路的总电容与各分电容的关系是( )。', '总电容<分电容', '总电容=分电容', '无关', '总电容>分电容');
INSERT INTO `xuanze` VALUES (14, '并联电路的总电容与各分电容的关系是( )。', '总电容>分电容', '无关', '总电容=分电容', '总电容<分电容');
INSERT INTO `xuanze` VALUES (15, '将220V、40W的灯泡与220V、100W的灯泡串联后接在380V的电源上，结果是( )。', '开始40W灯泡极亮随即烧毁', '灯泡均极亮随即烧毁', '两灯泡均比正常时较暗', '开始100W灯泡极亮随即烧毁');
INSERT INTO `xuanze` VALUES (16, '电功率的单位符号是( )。', 'W', 'kW•h', 'V•A', 'A');
INSERT INTO `xuanze` VALUES (17, '直流电路有功功率的表达式是 ( )。', 'Ｐ＝Ｉ２Ｒ', 'Ｐ＝ＩＵＲ', 'Ｐ＝Ｉ／Ｒ', 'Ｐ＝ＵＲ');
INSERT INTO `xuanze` VALUES (18, '绝缘电阻常用的单位符号是( )。', 'MΩ', 'mΩ', 'μΩ', 'Ω');
INSERT INTO `xuanze` VALUES (19, '电流所产生磁场的方向按( )确定。', '右手螺旋定则', '欧姆定律', '基尔霍夫定律', '楞次定律');
INSERT INTO `xuanze` VALUES (20, '白炽灯电路接近( )。', '纯电阻电路', '纯电感电路', '谐振电路', '纯电容电路');
INSERT INTO `xuanze` VALUES (21, '电容量的单位符号是( )。', 'F', 'S', 'T', 'C');
INSERT INTO `xuanze` VALUES (22, '我国生产用电和生活用电的额定频率为( )Hz。', '50', '55', '60', '45');
INSERT INTO `xuanze` VALUES (23, '功率三角形中，功率因数角所对的边是( )。', '无功功率', '瞬时功率', '有功功率', '视在功率');
INSERT INTO `xuanze` VALUES (24, '交流电路中功率因数的表达式是( )。', 'cosφ =R/Z', 'cosφ=X/Z', 'cosφ=(R-X)/Z', 'cosφ=(R+X)/Z');
INSERT INTO `xuanze` VALUES (25, '有功功率P、无功功率Q、视在功率S之间的关系是( )。', 'S²=P²+Q²', 'S=Q-P', 'S=P-Q', 'S=P+Q');
INSERT INTO `xuanze` VALUES (26, '对称三相交流电路有功功率的表达式P=3UＩcosφ中的电压和电流是( )。', '相电压和相电流', '线电压和线', '相电压和线电流', '线电压和相电流');
INSERT INTO `xuanze` VALUES (27, '三相不对称负载的中性线断开后，负载最大的一相的相电压将会( )。', '降低', '升高', '不变', '为零');
INSERT INTO `xuanze` VALUES (28, '由分立元件组成的单相桥式整流电路要用到( )只二极管。', '4', '2', '1', '3');
INSERT INTO `xuanze` VALUES (29, '三极管的基极用字母( )表示。', 'b', 'e', 'c', 'g');
INSERT INTO `xuanze` VALUES (30, '接在三相电源上的星形接法的对称三相负载，其线电压为相电压的( )倍。（根号表示为“√”）', '√3', '1', '√2', '1/√3');
INSERT INTO `xuanze` VALUES (31, '对地电压就是带电体与( )之间的电压。', '零电位大地', '接地体', '某一相线', '中性线');
INSERT INTO `xuanze` VALUES (32, '按安全管理要求以“250V以上”、“250V及以下”划分高压和低压时，250V指的是( )。', '对地电压', '相电压', '接触电压', '线电压');
INSERT INTO `xuanze` VALUES (33, '工频条件下，人的摆脱电流约为( )。', '10mA', '1mA', '100mA', '10A');
INSERT INTO `xuanze` VALUES (34, '工频条件下，人的平均感知电流约为( )。', '1mA', '10A', '100mA', '10mA');
INSERT INTO `xuanze` VALUES (35, '工频条件下，当电流持续时间超过心脏跳动周期时，室颤电流约为( )mA。', '50', '1', '100', '10');
INSERT INTO `xuanze` VALUES (36, '发生心室纤维性颤动时，血液循环( )。', '中止', '减缓', '加快', '变化不大');
INSERT INTO `xuanze` VALUES (37, '电流的瞬时作用引起的心室纤维性颤动，呼吸可能持续( )min。如不及时抢救，很快将导致生物性死亡', '2～3', '10', '5', '20');
INSERT INTO `xuanze` VALUES (38, '数10mA的电流通过人体短时间使人致命的最危险的原因是( )。', '引起心室纤维性颤动', '呼吸中止', '昏迷', '电弧灼伤');
INSERT INTO `xuanze` VALUES (39, '对于电击而言，工频电流与高频电流比较，其危险性是( ) 。', '工频危险性大', '二者危险性一样大', '二者不能比较', '高频危险性大');
INSERT INTO `xuanze` VALUES (40, '( )是最危险的电流途径。', '左手至胸部', '左手至脚', '右手至脚', '左手至右手');
INSERT INTO `xuanze` VALUES (41, '人体阻抗是由( )组成。', '电阻和电容', '纯电阻', '电阻和电感', '电容和电感');
INSERT INTO `xuanze` VALUES (42, '在干燥条件下，在接触电压100～220V的范围内，人体电阻大约为( )。', '1000～3000Ω', '100～300kΩ', '10～30kΩ', '100～300Ω');
INSERT INTO `xuanze` VALUES (43, '手持金属工具触及运行中的隔离开关的带电导体的电击是( )电击。', '直接接触', '感应电', '间接接触', '跨步电压');
INSERT INTO `xuanze` VALUES (44, '人站在地上，手直接触及已经漏电的电动机金属外壳的电击是( )电击。', '间接接触', '直接接触', '两线', '感应电');
INSERT INTO `xuanze` VALUES (45, '触电事故多的月份是( )月。', '6～9', '10～12', '2～4', '11～1');
INSERT INTO `xuanze` VALUES (46, '其他条件相同，人离接地点越近时可能承受的( )。', '跨步电压越大、接触电压越小', '跨步电压不变、接触电压越大', '跨步电压和接触电压都越大', '跨步电压越大、接触电压不变');
INSERT INTO `xuanze` VALUES (47, '在雷雨天气，跨步电压电击危险性较小的位置是( )。', '高大建筑物内', '大树下方', '高墙旁边', '电杆旁边');
INSERT INTO `xuanze` VALUES (48, '有( )以上的事故是由于误操作和违章作业造成的。', '85％', '50％', '60％', '40％');
INSERT INTO `xuanze` VALUES (49, '从触电( )min开始救治者，90%有效果。', '1', '20', '5', '10');
INSERT INTO `xuanze` VALUES (50, '胸外心脏挤压法的正确压点在( )。', '胸部正中，两乳连接水平', '心窝左上方', '心窝右上方', '心窝正下方');
INSERT INTO `xuanze` VALUES (51, '施行胸外心脏挤压法抢救时大约每分钟挤压( )次。', '100次左右', '20～30', '40～50', '5～10');
INSERT INTO `xuanze` VALUES (52, '施行口对口（鼻）人工呼吸时，大约每分钟进行( )次。', '10～12', '1～2', '60～80', '3～5');
INSERT INTO `xuanze` VALUES (53, '当触电人脱离电源后，如深度昏迷、呼吸和心脏已经停止，首先应当做的事情是( )。', '就地进行口对口（鼻）人工呼吸和胸外心脏按压抢救', '找急救车，等候急救车的到来', '紧急送往医院', '让触电人静卧');
INSERT INTO `xuanze` VALUES (54, '当触电人脱离电源后深度昏迷、心脏只有微弱跳动时( )注射肾上腺素。', '不允许', '允许中剂量', '允许大剂量', '允许小剂量');
INSERT INTO `xuanze` VALUES (55, 'ＩT系统属于( )系统。', '保护接地', 'PE线与N线共用的保护接零', 'PE线与N线前段共用后段分开的保护接零', 'PE线与N线全部分开的保护接零');
INSERT INTO `xuanze` VALUES (56, 'TN-S系统属于( )系统。', 'PE线与N线全部分开的保护接零', '保护接地', 'PE线与N线共用的保护接零', 'PE线与N线前段共用后段分开的保护接零');
INSERT INTO `xuanze` VALUES (57, 'TN-C系统属于( )系统。', '干线部分PE线与N线共用的保护接零', '保护接地', 'PE线与N线全部分开的保护接零', 'PE线与N线前段共用后段分开的保护接零');
INSERT INTO `xuanze` VALUES (58, '( )系统是不允许存在的。', 'TN-S-C', 'IT', 'TN-C', 'TT');
INSERT INTO `xuanze` VALUES (59, '在TN—S配电系统中，N线表示( )。', '中性线', '保护零线', '相线', '保护地线');
INSERT INTO `xuanze` VALUES (60, '在TN—S配电系统中，PE线表示( )。', '保护地线', '相线', '中性线', '工作零线');
INSERT INTO `xuanze` VALUES (61, '在TN—C配电网中，PEN线表示( )。', '工作与保护共用的零线', '中性线', '保护地线', '保护零线');
INSERT INTO `xuanze` VALUES (62, 'TN系统分为( )种方式。', '三', '二', '一', '四');
INSERT INTO `xuanze` VALUES (63, '在380V低压IT系统中，一般要求保护接地电阻≤( )Ω', '4', '20', '30', '10');
INSERT INTO `xuanze` VALUES (64, '配电变压器低压中性点的接地叫做( )。', '系统接地', '防雷接地', '保护接地', '重复接地');
INSERT INTO `xuanze` VALUES (65, '在TN-S系统中，用电设备的金属外壳应当接( )干线。', 'PE', 'PEN', '接地', 'N');
INSERT INTO `xuanze` VALUES (66, '在TN-C系统中，用电设备的金属外壳应当接( )干线。', 'PEN', 'PE', '接地', 'N');
INSERT INTO `xuanze` VALUES (67, '在同一保护接零系统中，如某设备接零确有困难而采用接地保护，则应采取( )作为补充安全措施。', '加装漏电保护器', '改用小容量熔断器', '降低接地电阻', '电源主开关改用低压断路器');
INSERT INTO `xuanze` VALUES (68, '重复接地的安全作用不包括( )。', '减轻线路过负荷的危险', '改善架空线路的防雷性能', '减轻零线断开的危险', '降低漏电设备的对地电压');
INSERT INTO `xuanze` VALUES (69, '重复接地的接地电阻值一般不应超过( )。', '10Ω', '50Ω', '30Ω', '100Ω');
INSERT INTO `xuanze` VALUES (70, '当保护线与相线材料相同，相线截面积大于35mm²时，保护线截面积不得小于相线的( )。', '1/2', '2/3', '1/4', '1/3');
INSERT INTO `xuanze` VALUES (71, '利用单芯绝缘导线作PE线，在有机械防护的条件下，其截面积不得小于( )mm²。', '2.5', '4', '6', '10');
INSERT INTO `xuanze` VALUES (72, '低压配电系统的铜质PEN线的截面积不得小于( )mm²。', '10', '2.5', '6', '4');
INSERT INTO `xuanze` VALUES (73, '低压配电系统的铝质PEN线的截面积不得小于( )mm²。', '16', '6', '4', '10');
INSERT INTO `xuanze` VALUES (74, '利用低压配电系统的多芯电缆芯线作PE线或PEN线时，该芯线的截面积不得小于( )mm²。', '4', '2.5', '1.5', '6');
INSERT INTO `xuanze` VALUES (75, '低压配电系统的PE线应当为( )色线。', '黄绿双', '黑', '蓝', '黄');
INSERT INTO `xuanze` VALUES (76, '室外接地干线地上部分采用镀锌圆钢时，其直径不得小于( )mm。', '8', '4', '6', '10');
INSERT INTO `xuanze` VALUES (77, '接地体采用镀锌圆钢时，其直径不得小于( )mm。', '10', '8', '4', '6');
INSERT INTO `xuanze` VALUES (78, '室外接地干线采用扁钢时，其截面应不小于( )mm²。', '100', '75', '24', '48');
INSERT INTO `xuanze` VALUES (79, '接地装置地下部分应采用搭接焊，圆钢焊接长度不应小于其直径的( )倍。', '6', '2', '4', '3');
INSERT INTO `xuanze` VALUES (80, '接地装置地下部分应采用焊接，并采用搭接焊，扁钢焊接长度不应小于其宽度的( )倍。', '2', '6', '4', '3');
INSERT INTO `xuanze` VALUES (81, '电力设备接地体与独立避雷针接地体之间的最小距离为( )m。', '3', '4', '1', '2');
INSERT INTO `xuanze` VALUES (82, '电力设备接地体与建筑物墙基之间的最小距离为( )m。', '1.5', '2', '1', '0.5');
INSERT INTO `xuanze` VALUES (83, '车间接地装置定期测量接地电阻的周期为( )年。', '1', '3', '半', '2');
INSERT INTO `xuanze` VALUES (84, '变、配电站接地装置每( )年检查一次。', '1', '2', '半', '3');
INSERT INTO `xuanze` VALUES (85, '各种防雷接地装置每( )年在雷雨季前检查一次。', '1', '2', '半', '3');
INSERT INTO `xuanze` VALUES (86, '爆炸危险物质分共为( )类。', '三', '二', '四', '一');
INSERT INTO `xuanze` VALUES (87, '爆炸性气体、蒸气属于( )类。', 'Ⅱ', 'Ⅰ', 'Ⅲ', '四');
INSERT INTO `xuanze` VALUES (88, '矿井甲烷属于( ) 类。', 'Ⅰ', 'Ⅱ', 'Ⅲ', '四');
INSERT INTO `xuanze` VALUES (89, '正常运行时连续或长时间出现或短时间频繁出现爆炸性气体、蒸气或薄雾的区域，如油罐内部液面上部空间为( )区。', '0区', '3区', '1区', '2区');
INSERT INTO `xuanze` VALUES (90, '正常运行时不出现，即使出现也只可能是短时间偶然出现爆炸性气体、蒸气或薄雾的区域，如油罐外3m内为( )区。', '2区', '1区', '0区', '3区');
INSERT INTO `xuanze` VALUES (91, '火灾危险环境按规定分为21区、22区和23区。具有闪点高于环境温度的可燃液体，在数量和配置上能引起火灾危险的环境，属于( )区。', '21区', '23区', '22区', '不确定');
INSERT INTO `xuanze` VALUES (92, '火灾危险环境按规定分为21区、22区和23区。具有固体状可燃物质，在数量和配置上能引起火灾危险的环境，属于( )区。', '23区', '21区', '22区', '不清楚');
INSERT INTO `xuanze` VALUES (93, '用于爆炸性气体环境的防爆电气设备结构型式及符号为：隔爆型（ ）。', 'd', 'c', 'b', 'a');
INSERT INTO `xuanze` VALUES (94, '用于爆炸性气体环境的防爆电气设备结构型式及符号为：增安型（ ）。', 'e', 'a', 'd', 'b');
INSERT INTO `xuanze` VALUES (95, '在爆炸危险环境，低压电力、照明线路所用电线和电缆的额定电压不得低于工作电压，并不得低于（ ）V。', '500', '380', '100', '220');
INSERT INTO `xuanze` VALUES (96, '1区、2区导体允许载流量不应小于熔断器熔体额定电流和断路器长延时过电流脱扣器整定电流的（ ）倍。', '1.25', '2.5', '1.1', '2');
INSERT INTO `xuanze` VALUES (97, '油量（ ）kg者必须安装在有防爆隔墙的间隔内。', '60～600', '50', '30', '40');
INSERT INTO `xuanze` VALUES (98, '油量（ ）kg以上者必须安装在单独的防爆间隔内。', '600', '300', '400', '500');
INSERT INTO `xuanze` VALUES (99, '在爆炸危险环境应将保护线与中性线分开。保护导线的最小截面，铜导体不得小于（ ）mm²、钢导体不得小于6mm²。', '4', '2.5', '1', '1.5');
INSERT INTO `xuanze` VALUES (100, '干粉、二氧化碳等灭火器喷嘴至10kV带电体的距离不得小于（ ）m。', '0.4', '0.1', '0.3', '0.2');
INSERT INTO `xuanze` VALUES (101, '对架空线路等空中设备灭火时，人与带电体之间的仰角不应超过（ ）。', '45°', '90°', '60°', '30°');
INSERT INTO `xuanze` VALUES (102, '直接测量交流电压应当选用( )仪表。', '电磁系', '电动系', '整流系', '磁电系');
INSERT INTO `xuanze` VALUES (103, '直接测量直流电流应当选用( )仪表。', '磁电系', '电磁系', '电动系', '感应系');
INSERT INTO `xuanze` VALUES (104, '磁电系仪表的特点之一是( )。', '灵敏度高', '交直流两用', '结构简单', '内阻小');
INSERT INTO `xuanze` VALUES (105, '电磁系测量机构没有( )。', '反作用弹簧', '可动铁心', '线圈', '游丝及阻尼片');
INSERT INTO `xuanze` VALUES (106, '感应系仪表主要用于计量( )。', '交流电能', '交流电流', '直流电能', '交流电压');
INSERT INTO `xuanze` VALUES (107, '从工作机构上看，电能表属于( )系仪表。', '感应', '磁电', '电动', '电磁');
INSERT INTO `xuanze` VALUES (108, '电流表的量程应当按工作电流的( )倍左右选取。', '1.5', '1', '2', '2.5');
INSERT INTO `xuanze` VALUES (109, '应用磁电系电流表测量直流大电流，可以( )扩大量程。', '并联分流电阻', '调整反作用弹簧', '应用电流互感器', '串联电阻');
INSERT INTO `xuanze` VALUES (110, '应用电磁系电流表测量交流大电流，可以( )扩大量程。', '应用电流互感器', '并联分流电阻', '串联分压电阻', '应用电压互感器');
INSERT INTO `xuanze` VALUES (111, '应用磁电系电压表测量直流高电压，可以( )扩大量程。', '串联分压电阻', '并联电阻', '调整反作用弹簧', '应用电压互感器');
INSERT INTO `xuanze` VALUES (112, '安装在交流开关柜上的电压表多为( )系电压表。', '电磁', '感应', '磁电', '电动');
INSERT INTO `xuanze` VALUES (113, '电工仪表共分( )个准确等级。', '7', '6', '4', '5');
INSERT INTO `xuanze` VALUES (114, '电工仪表的精确度等级用( )表示。', '引用相对误差', '真值相对误差', '示值相对误差', '绝对误差');
INSERT INTO `xuanze` VALUES (115, '就对被测电路的影响而言，电压表的内阻( )。', '越大越好', '大小均可', '越小越好', '适中为好');
INSERT INTO `xuanze` VALUES (116, '万用表不可以用来测量( )。', '功率', '电感', '交流电压', '电阻');
INSERT INTO `xuanze` VALUES (117, '用指针式万用表测量交流电压时，其测量机构属于( )测量机构。', '磁电整流系', '静电系', '电磁系', '磁电系');
INSERT INTO `xuanze` VALUES (118, '用万用表倍率1k档测量电阻，指针指示50Ω，则被测电阻为( )Ω。', '50000', '50', '5000', '500');
INSERT INTO `xuanze` VALUES (119, '万用表的欧姆调零旋钮应当在( )将指针调整至零位。', '换档后测量电阻前', '测量电压或电流后', '测量电阻后', '测量电压或电流前');
INSERT INTO `xuanze` VALUES (120, '测量电阻时选挡的原则是应使指针指在标尺的中心( )左右范围内。', '1／2', '1／3', '1／4', '1／5');
INSERT INTO `xuanze` VALUES (121, '磁电系钳形电流表可用于测量( )。', '工频交流电流', '直流电流', '高频非正弦波电流', '上述三种电流');
INSERT INTO `xuanze` VALUES (122, '兆欧表手摇发电机输出的电压是( )。', '直流电压', '交流电压', '高频电压', '脉冲电压');
INSERT INTO `xuanze` VALUES (123, '尚未转动兆欧表的摇柄时，水平放置完好的兆欧表的指针应当指在( )。', '随机位置', '刻度盘正中央', '刻度盘最左端', '刻度盘最右端');
INSERT INTO `xuanze` VALUES (124, '做兆欧表的开路和短路试验时，转动摇柄的正确做法是( )。', '缓慢摇动加速至120r/min，指针稳定后缓慢减速至停止', '快速摇动加速至120r/min，指针稳定后缓慢减速至停止', '缓慢摇动加速至120r/min，指针稳定后快速减速至停止', '快速摇动加速至120r/min，指针稳定后快速减速至停止');
INSERT INTO `xuanze` VALUES (125, '兆欧表有“L”、“E”和“G”三个端钮。其中，“G”端钮的测试线在测电缆时应接在( )。', '接被测线芯的绝缘', '作接地保护', '作机械调零', '接被测导体');
INSERT INTO `xuanze` VALUES (126, '摇测低压电力电缆的绝缘电阻所采用兆欧表的额定电压为( )V。', '1000', '2500', '500', '250');
INSERT INTO `xuanze` VALUES (127, '接地电阻测量仪分三接线端子和四接线端子两种，其中( )m的一根用于电流探针）。', '40', '10', '5', '20');
INSERT INTO `xuanze` VALUES (128, '电能表的作用是用来测量( )的仪表。', '电能', '电功率', '负荷电流', '电源电压');
INSERT INTO `xuanze` VALUES (129, '用一只电能表计量三相四线不平衡负荷电路的有功电能，应选用( )电能表。', '三相三元件有功', '单相有功', '三相两元件有功', '三相无功');
INSERT INTO `xuanze` VALUES (130, '功率因数表的指示值是( )功率因数。', '瞬时', '小时平均', '月平均', '日平均');
INSERT INTO `xuanze` VALUES (131, '智能电能表可足不出户对用户进行( )抄表。', '以上三项', '尖、平', '峰', '谷');
INSERT INTO `xuanze` VALUES (132, '( )组合是在低压操作中使用的基本安全用具。', '绝缘手套、试电笔、带绝缘柄的工具', '绝缘鞋、试电笔、带绝缘柄的工具', '绝缘手套、试电笔、绝缘鞋', '试电笔、绝缘靴、绝缘垫');
INSERT INTO `xuanze` VALUES (133, '绝缘手套的长度应保证戴上后超过手腕( )mm。', '100', '30', '50', '10');
INSERT INTO `xuanze` VALUES (134, '绝缘手套在对地电压( )V以下电压区作业时，可作为基本安全用具。', '250', '500', '380', '220');
INSERT INTO `xuanze` VALUES (135, '( )V以上高压操作应使用绝缘靴，还可用于防跨步电压。', '1000', '500', '5000', '380');
INSERT INTO `xuanze` VALUES (136, '绝缘手套和绝缘靴试验包括( )。', '交流耐压试验和泄漏电流试验', '绝缘电阻试验、耐压试验和泄漏电流试验', '绝缘电阻试验和泄漏电流试验', '绝缘电阻试验和耐压试验');
INSERT INTO `xuanze` VALUES (137, '验电笔只能在( )V及以下的电压系统和设备上使用。', '380', '2500', '500', '1000');
INSERT INTO `xuanze` VALUES (138, '试电笔不可用来( )。', '判断电流大小', '判断有电无电', '判断电压高低', '区别相线和中性线');
INSERT INTO `xuanze` VALUES (139, '试电笔不可用来( )。', '读取电阻数值', '区别相线和中性线', '判断交流直流', '判断有电无电');
INSERT INTO `xuanze` VALUES (140, '绝缘垫厚度不应小于( )mm。', '5', '4', '2', '3');
INSERT INTO `xuanze` VALUES (141, '绝缘垫宽度不应小于( )mm。长度根据需要。', '800', '400', '600', '1200');
INSERT INTO `xuanze` VALUES (142, '绝缘台的支持绝缘子高度不应小于( )cm。', '10', '15', '20', '5');
INSERT INTO `xuanze` VALUES (143, '绝缘台的长度和宽度均不应小于800mm，也不宜大于( )m。', '1.5X1.5', '1', '0.6', '0.8');
INSERT INTO `xuanze` VALUES (144, '绝缘台的定期试验一般每( )年进行一次。', '3', '1', '4', '2');
INSERT INTO `xuanze` VALUES (145, '靠梯与地面的夹角以( )左右为宜。', '60', '45', '75', '30');
INSERT INTO `xuanze` VALUES (146, '安全腰带是防止坠落的安全用具，宽度不应小于( )mm', '60', '50', '70', '40');
INSERT INTO `xuanze` VALUES (147, '在电气上用 ( ) 三色分别代表L1、L2、L3三个相序。', '黄、绿、红', '红、白、蓝', '红、绿、黄', '黄、蓝、黑');
INSERT INTO `xuanze` VALUES (148, '线路上( )色代表中性线。', '淡蓝', '黄绿双', '白', '黑');
INSERT INTO `xuanze` VALUES (149, '用黄绿双色绝缘导线代表( )线。', 'PE', 'PEN', 'N', 'L');
INSERT INTO `xuanze` VALUES (150, '移动使用的标示牌要用硬质( )材料制成。', '绝缘', '木质', '铝', '铁质');
INSERT INTO `xuanze` VALUES (151, '“禁止合闸，有人工作！”标示牌的颜色应该是( )。', '白底红字', '黑底白字', '白底黑字', '红底白字');
INSERT INTO `xuanze` VALUES (152, '禁止攀登、高压危险！标示牌的字色应该是( )。', '黑', '白', '绿', '红');
INSERT INTO `xuanze` VALUES (153, '电工用钳有钢丝钳、尖嘴钳、偏口钳、剥线钳等。手柄绝缘耐压为( )V。', '500', '1000', '380', '1500');
INSERT INTO `xuanze` VALUES (154, '手动导线压接钳利用杠杆原理工作，多用于截面( )mm²以下的导线接头的钳接管压接。', '35', '16', '25', '50');
INSERT INTO `xuanze` VALUES (155, '手提式油压钳用于截面( )mm²及以上的导线的钳接管压接。', '16', '25', '35', '50');
INSERT INTO `xuanze` VALUES (156, '对面积较大的工件进行搪锡处理需选用( )W电烙铁。', '300', '40', '150', '75');
INSERT INTO `xuanze` VALUES (157, '单相手持电动工具的控制开关为，( )级漏电保护开关。', '两', '四', '三', '单');
INSERT INTO `xuanze` VALUES (158, 'Ⅲ类工具过去都采用36V，现“国标”规定为( )V。', '42', '12', '24', '36');
INSERT INTO `xuanze` VALUES (159, '使用Ⅰ类工具，必须装设额定漏电动作电流不大于( )mA、动作时间不大于0.1s的剩余电流动作保护装置。', '30', '50', '15', '20');
INSERT INTO `xuanze` VALUES (160, 'Ⅰ类设备应有良好的接保护线，采用截面积( )mm²以上的多股软铜线。', '1.5', '4', '2.5', '1');
INSERT INTO `xuanze` VALUES (161, 'Ⅰ类设备绝缘电阻不低于( )MΩ，Ⅱ类设备不低于7MΩ。', '2', '5', '0.5', '1');
INSERT INTO `xuanze` VALUES (162, '交流弧焊机的二次空载电压为( )V左右，二次额定工作电压为30V左右。', '70', '100', '30', '50');
INSERT INTO `xuanze` VALUES (163, '弧焊机的一次绝缘电阻不应低于1MΩ、二次绝缘电阻不应低于( )MΩ。', '0.5', '2', '5', '1');
INSERT INTO `xuanze` VALUES (164, '电工防护用品包括防护眼镜、手套、( )等。', '安全帽', '铁扳手', '电工钳', '试电笔');
INSERT INTO `xuanze` VALUES (165, '低压电器一般指的是用于交流额定电压( )V及以下的电路中。', '1200', '1000', '1500', '500');
INSERT INTO `xuanze` VALUES (166, '隔离开关在合闸状态时，正确的安装方位是操作手柄向( )。', '上', '下', '右', '左');
INSERT INTO `xuanze` VALUES (167, '隔离开关与断路器串联安装使用时，拉闸顺序是( )。', '先断开断路器后断开刀开关', '无先后顺序要求', '同时断开断路器和刀开关', '先断开刀开关后断开断路器');
INSERT INTO `xuanze` VALUES (168, '用低压隔离开关控制异步电动机时，开关额定电流不应小于电动机额定电流的( )倍。', '3', '2', '1.5', '2.5');
INSERT INTO `xuanze` VALUES (169, '低压断路器的瞬时动作电磁式过电流脱扣器的作用是( )。', '短路保护', '漏电保护', '缺相保护', '过载保护');
INSERT INTO `xuanze` VALUES (170, 'DZ型低压断路器的热脱扣器的作用是( )。', '过载保护', '漏电保护', '缺相保护', '短路保护');
INSERT INTO `xuanze` VALUES (171, '低压断路器的最大分断电流( )其额定电流。', '远大于', '等于', '略小于', '略大于');
INSERT INTO `xuanze` VALUES (172, 'DW型低压断路器的瞬时动作过电流脱扣器动作电流的调整范围多为额定电流的( )倍。', '1～3', '7～9', '4～6', '10～20');
INSERT INTO `xuanze` VALUES (173, '接触器的通断能力应当是( )。', '不能切断短路电流，能通过短路电流', '能切断和通过短路电流', '能切断短路电流，不能通过短路电流', '不能切断和通过短路电流');
INSERT INTO `xuanze` VALUES (174, '断路器的分励脱扣器及失压脱扣器，当电压低于额定值的％( )时，失压脱扣器应能可靠释放。', '35', '30', '50', '40');
INSERT INTO `xuanze` VALUES (175, '选用交流接触器应全面考虑( )的要求。', '额定电流、额定电压、吸引线圈电压、辅助接点数量', '额定电流、额定电压、辅助接点数量', '额定电压、吸引线圈电压、辅助接点数量', '额定电流、额定电压、吸引线圈电压');
INSERT INTO `xuanze` VALUES (176, '交流接触器本身可兼作( )保护。', '失压', '过载', '短路', '缺相');
INSERT INTO `xuanze` VALUES (177, '用接触器控制一台10kW三相异步电动机时，宜选用额定电流( )A的交流接触器。', '40', '10', '100', '20');
INSERT INTO `xuanze` VALUES (178, '用交流接触器控制一台连续运行的三相异步电动机时，接触器的额定电流可按电动机额定电流的( )倍选择。', '1.3～2', '1.1～1.3', '1.5～2.5', '2.5～3.5');
INSERT INTO `xuanze` VALUES (179, '磁力起动器主要由( )组成。', '接触器、按钮、热继电器', '接触器、熔断器、热继电器', '断路器、热继电器、按钮', '接触器、熔断器、按钮');
INSERT INTO `xuanze` VALUES (180, '对于频繁起动的异步电动机，应当选用的控制电器是( )。', '接触器', '低压断路器', '铁壳开关', '转换开关');
INSERT INTO `xuanze` VALUES (181, '无填料封闭管式熔断器一般都属于( )熔断器。', '纤维管式', '防护式', '开启式', '封闭式');
INSERT INTO `xuanze` VALUES (182, '下列断流容量最大的熔断器是( )熔断器。', '有填料封闭管式', '瓷插式', '纤维管式', '开启式');
INSERT INTO `xuanze` VALUES (183, '对于三相异步电动机，熔体额定电流应选为电动机额定电流的( )倍。', '1.5～2.5', '5～7', '3.5～4.5', '2.5～3.5');
INSERT INTO `xuanze` VALUES (184, '用熔断器保护一台20kW的三相异步电动机时，应选用( )A的熔体。', '60~80', '40', '150', '200');
INSERT INTO `xuanze` VALUES (185, '当负荷电流达到熔断器熔体的额定电流时，熔体将( )。', '不会熔断', '短延时后熔断', '长延时后熔断', '立即熔断');
INSERT INTO `xuanze` VALUES (186, '热继电器属于( )电器。', '保护', '控制', '开关', '主令');
INSERT INTO `xuanze` VALUES (187, '热继电器的温感元件是( )。', '双金属片', '易熔元件', '控制触头', '电磁机构');
INSERT INTO `xuanze` VALUES (188, '热继电器的动作时间随着电流的增大而( )。', '缩短', '缓慢延长', '急剧延长', '保持不变');
INSERT INTO `xuanze` VALUES (189, '热继电器的动作电流整定值是可以调节的，调节范围大约是热元件额定电流的( )。', '60%～100%', '50%～60%', '100%～200%', '50%～150%');
INSERT INTO `xuanze` VALUES (190, '热继电器双金属片受热后将发生( )变形。', '弯曲', '伸长', '膨胀', '破坏');
INSERT INTO `xuanze` VALUES (191, '采用热继电器作为三相异步电动机的过载保护元件时，应将热元件的动作电流整定为电动机额定电流的( )倍。', '1', '2～2.5', '1～1.5', '1.5～2');
INSERT INTO `xuanze` VALUES (192, '行程开关属于( )电器。', '主令', '保护', '开关', '控制');
INSERT INTO `xuanze` VALUES (193, '交流接触器的文字代号是（ ）。', 'KM', 'QS', 'QF', 'FR');
INSERT INTO `xuanze` VALUES (194, '断路器的文字代号是（ ）。', 'QF', 'QS', 'FR', 'KM');
INSERT INTO `xuanze` VALUES (195, '刀开关（刀闸）的文字代号是（ ）。', 'QS', 'QF', 'KM', 'FR');
INSERT INTO `xuanze` VALUES (196, '热继电器的文字代号是（ ）。', 'FR', 'QF', 'QS', 'KM');
INSERT INTO `xuanze` VALUES (197, '异步电动机的定子铁心由厚( )mm，表面有绝缘层的硅钢片叠压而成。', '0.35～0.5', '1～1.5', '1.5～2', '0.5～1');
INSERT INTO `xuanze` VALUES (198, '中、小型异步电动机定子与转子间的气隙为( )mm。', '0.2～2', '2～5', '0.02～0.2', '5～10');
INSERT INTO `xuanze` VALUES (199, '异步电动机鼠笼型转子每个槽内有( )条转子导条。', '1', '3', '4', '2');
INSERT INTO `xuanze` VALUES (200, '电动机在额定电压下定子三相绕组的连接方法，有( )种。', '二', '一', '四', '三');
INSERT INTO `xuanze` VALUES (201, '绕线型异步电动机的三相转子绕组的连接方式是( )。', '星形连接', '串联', '三角形连接', '并联');
INSERT INTO `xuanze` VALUES (202, '带有电刷和滑环的电动机是( )。', '绕线型异步电动机', '大容量鼠笼型异步电动机', '中容量鼠笼型异步电动机', '小容量鼠笼型异步电动机');
INSERT INTO `xuanze` VALUES (203, '异步电动机旋转磁场的转速与极数( )。', '成反比', '的平方成正比', '无关', '成正比');
INSERT INTO `xuanze` VALUES (204, '四极异步电动机的同步转速是( )r/min。', '1500', '3000', '750', '1000');
INSERT INTO `xuanze` VALUES (205, '六极异步电动机的同步转速是( )r/min。', '1000', '750', '1500', '3000');
INSERT INTO `xuanze` VALUES (206, '在电动机状态，异步电动机的实际转速( )同步转速。', '略低于', '明显高于', '明显低于', '略高于');
INSERT INTO `xuanze` VALUES (207, '异步电动机在电动机状态时，转速、转差率分别为( )。', '转速低于同步转速，转差率小于l', '转速低于同步转速，转差率大于1', '转速高于同步转速，转差率小于1', '转速高于同步转速，转差率大于1');
INSERT INTO `xuanze` VALUES (208, '中小型三相异步电动机在额定工作状态下运行时，转差率为( )左右。', '0.02～0.06', '10', '0.005', '1');
INSERT INTO `xuanze` VALUES (209, '三相异步电动机的额定电压指的是( )。', '线电压有效值', '线电压最大值', '相电压有效值', '相电压最大值');
INSERT INTO `xuanze` VALUES (210, '异步电动机的额定功率是( )功率。', '转子轴输出的机械功率', '电磁功率', '输入的视在功率', '输入的有功功率');
INSERT INTO `xuanze` VALUES (211, '电动机的输出功率与输入功率的比值是其( )。', '效率', '功率因数', '有功功率', '视在功率');
INSERT INTO `xuanze` VALUES (212, '异步电动机全压起动时，起动瞬间的电流高达电动机额定电流的( )倍。', '4～7', '3～4', '8～9', '2～3');
INSERT INTO `xuanze` VALUES (213, '三相异步电动机的额定电压为380V、额定电流为28A、cosφ=0.8、η=0.9，该电动机的额定功率约为（ ）kW。', '14', '10', '28', '20');
INSERT INTO `xuanze` VALUES (214, '电动机的机械特性是( )的关系。', '转速与转矩', '转速与电流', '转速与电压', '电压与转矩');
INSERT INTO `xuanze` VALUES (215, '异步电动机的电磁转矩与电源电压的( )次方成正比。', '2', '4', '3', '1');
INSERT INTO `xuanze` VALUES (216, '三相异步电动机采用自耦减压起动器80％的抽头起动时，堵转转距为全压起动的( )。', '64%', '100%', '80%', '40%');
INSERT INTO `xuanze` VALUES (217, '三相异步电动机采用自耦减压起动器80％的抽头起动时，线路电流为全压起动的( )。', '64%', '40%', '100%', '80%');
INSERT INTO `xuanze` VALUES (218, '三相异步电动机采用自耦减压起动器65％的抽头起动时，电动机起动电流为全压起动的( )。', '42%', '80%', '64%', '100%');
INSERT INTO `xuanze` VALUES (219, '三角形接线的三相笼式异步电动机采用Ｙ-△起动时，堵转转矩为全压起动的( )。（根号表示为“√”）', '1/3', '100%', '1/2', '1/√3');
INSERT INTO `xuanze` VALUES (220, '三角形接线的三相鼠笼式异步电动机采用Ｙ-△起动时，线电流为全压起动的( )。（根号表示为“√”）', '1/3', '100%', '1/2', '1/√3');
INSERT INTO `xuanze` VALUES (221, '三角形接线的三相异步电动机运行中，绕组相电流为线电流的( )。（根号表示为“√”）', '1/√3', '100%', '1/3', '1/2');
INSERT INTO `xuanze` VALUES (222, '交流异步电动机的变极调速是通过改变( )来实现的。', '定子绕组的连接方式', '电源频率', '转子外接电阻', '电源电压');
INSERT INTO `xuanze` VALUES (223, '改变( )不能改变异步电动机转速。', '功率因数', '转差率', '磁极对数', '电源频率');
INSERT INTO `xuanze` VALUES (224, '绕线式异步电动机一般利用改变( )的方法进行调速。', '转子电路中的电阻', '电源频率', '电源电压', '磁极对数');
INSERT INTO `xuanze` VALUES (225, '下列四组相序中，唯一相反的一组相序是( )。', 'A-C-B', 'A-B-C', 'B-C-A', 'C-A-B');
INSERT INTO `xuanze` VALUES (226, '在电动机输出力不变的情况下，一般电源电压允许变化范围为( )。', '+10％～-5％', '-5%~+5%', '7%', '-10%~+10%');
INSERT INTO `xuanze` VALUES (227, '三相异步电动机恒载运行时，三相电源电压突然降低10％，其电流将( )。', '略有增大', '略有减小', '上下波动', '保持不变');
INSERT INTO `xuanze` VALUES (228, '三相异步电动机恒载运行时，三相电源电压突然升高10％，其电流将( )。', '略有减小', '上下波动', '略有增大', '保持不变');
INSERT INTO `xuanze` VALUES (229, '三相异步电动机空载运行的效率与满载运行相比，结果是( )。', '满载时效率高', '二者相同', '空载时效率高', '无法判断');
INSERT INTO `xuanze` VALUES (230, '怀疑电动机定子绕组存在匝间短路时，应在退出运行后使用( )进行测量判断。', '万用表及电桥', '电流表', '500V兆欧表', '电压表');
INSERT INTO `xuanze` VALUES (231, '怀疑电动机定子绕组存在接地故障时，应在退出运行后使用( )进行测量判断。', '兆欧表', '万用表及电桥', '电压表', '电流表');
INSERT INTO `xuanze` VALUES (232, '单相异步电动机有( )组定子绕组。', '2', '4', '3', '1');
INSERT INTO `xuanze` VALUES (233, '单相电容起动异步电动机的( )组定子绕组在起动时串联有电容器。', '1', '3', '4', '2');
INSERT INTO `xuanze` VALUES (234, '串励电动机的转速能达到( )r/min以上。', '20000', '1500', '3000', '1000');
INSERT INTO `xuanze` VALUES (235, '并联电容器容量的单位是( )。', 'kvar', 'kVA', 'F', 'kW');
INSERT INTO `xuanze` VALUES (236, '并联电容器所在环境日平均最高温度不应超过( ) ℃。', '40', '50', '35', '45');
INSERT INTO `xuanze` VALUES (237, '当用电单位总功率因数低于( )时，应投入并联电容器。', '0.9', '0.85', '0.95', '0.8');
INSERT INTO `xuanze` VALUES (238, '运行中的并联电容器的外壳温度，如无厂家提供的数据，一般不应超过( )℃。', '60', '70', '50', '40');
INSERT INTO `xuanze` VALUES (239, '并联电容器不能提高( )。', '用电设备功率因数', '供电设备出力', '线路功率因数', '电压质量');
INSERT INTO `xuanze` VALUES (240, '并联电容器不能提高( )。', '配电变压器容量', '电压质量', '线路功率因数', '供电效率');
INSERT INTO `xuanze` VALUES (241, '并联电容器投入过多的结果是使线路功率因数( )。', '超前<1', '>0', '>1', '<1');
INSERT INTO `xuanze` VALUES (242, '并联电容器分层安装时，一般不超过( )层。', '3', '2', '5', '1');
INSERT INTO `xuanze` VALUES (243, '三相并联电容器分组安装时，每组一般不宜超过( )台。', '4', '12', '8', '16');
INSERT INTO `xuanze` VALUES (244, '相邻并联电容器之间的距离不得小于( ) cm。', '5～10', '1～2', '3～4', '4～5');
INSERT INTO `xuanze` VALUES (245, '并联电容器组和总容量( ) kvar及以上的低压电容器组每相应装电流表。', '30', '60', '2000', '100');
INSERT INTO `xuanze` VALUES (246, '总容量( )kvar及以上的低压并联电容器组应装电压表。', '60', '30', '100', '2000');
INSERT INTO `xuanze` VALUES (247, '并联电容器运行中电流不应长时间超过电容器额定电流的( )倍。', '1.3', '1.2', '1.5', '1.1');
INSERT INTO `xuanze` VALUES (248, '并联电容器运行中电压不应长时间超过电容器额定电压的( )倍。', '1.1', '1.2', '1.3', '1.5');
INSERT INTO `xuanze` VALUES (249, '并联电容器不得在其带有残留电荷的情况下合闸。电容器重新合闸前，至少应放电( )min。', '3', '10', '1', '2');
INSERT INTO `xuanze` VALUES (250, '用于三相并联电容器放电的白炽灯泡采用( )连接的较多。', '三角形', '串联', '并联', '星形');
INSERT INTO `xuanze` VALUES (251, '低压并联电容器组总容量超过( )kvar时，应采用低压断路器保护和控制。', '100', '300', '200', '400');
INSERT INTO `xuanze` VALUES (252, '保护单台并联电容器的熔断器熔体的额定电流应按并联电容器额定电流的( )倍选用。', '1.5～2.5', '3～5', '1.3～1.8', '1.15～1.25');
INSERT INTO `xuanze` VALUES (253, '保护多台电容器可按电容器额定电流之和的( )倍选用熔体的额定电流。', '1.3～1.8', '1.15～1.25', '1.5～2.5', '3～5');
INSERT INTO `xuanze` VALUES (254, '测量并联电容器的绝缘电阻，合格值的标准是：运行中的并联电容器不得低于( )MΩ。', '1000', '0.1', '10', '1');
INSERT INTO `xuanze` VALUES (255, '发生下列( )故障情况之一时，电容器组应紧急退出运行。', '绝缘套管严重闪络放电', '电压偏高', '电流偏高', '电压偏低');
INSERT INTO `xuanze` VALUES (256, '事故照明一般采用( )V的电压，以便与工作照明线路互相切换。', '220', '24', '42', '36');
INSERT INTO `xuanze` VALUES (257, '在特别潮湿场所、高温场所、有导电灰尘的场所或有导电地面的场所，对于容易触及而又无防止触电措施的固定式灯具，且其安装高度不足2.2m时，应采用( )V安全电压。', '24', '12', '220', '36');
INSERT INTO `xuanze` VALUES (258, '恶劣工作环境，如坑道、金属容器中的移动照明应采用( )V工作电压。', '12', '42', '24', '36');
INSERT INTO `xuanze` VALUES (259, '室内或建筑工地多采用铜芯硬线，最小截面不小于( )mm²。', '1', '0.5', '2.5', '1.5');
INSERT INTO `xuanze` VALUES (260, '以气体放电灯为主要负荷的三相四线电路中，中性线截面不应小于( )。', '相线截面', '相线截面的2/3', '相线截面的1/3', '相线截面的1/2');
INSERT INTO `xuanze` VALUES (261, '小于400W的高压水银灯、高压钠灯的导线截面不小于( ) mm²。', '1.5', '4', '2.5', '1');
INSERT INTO `xuanze` VALUES (262, '照明线路允许电压损失，规定为额定电压的( )。', '5％～10％', '±5%', '±5%～±7%', '±10%');
INSERT INTO `xuanze` VALUES (263, '室内每一照明支路上所接灯具（包括插座），原则上不超过( )个。', '20～25', '50～100', '10～15', '30～40');
INSERT INTO `xuanze` VALUES (264, '断路器过流脱扣电流值不应大于( )A。', '15A', '10A', '30A', '25A');
INSERT INTO `xuanze` VALUES (265, '由公共低压配电网配电的照明负荷，( )A以上应采用三相四线配电。', '30', '20', '100', '50');
INSERT INTO `xuanze` VALUES (266, '室内非生产环境的单相插座工作电流一般可按( )A考虑。', '6', '1', '1.5', '2.5');
INSERT INTO `xuanze` VALUES (267, '灯具重量超过( )kg，应采用专用的、标准合格的预埋件和吊装件。', '3', '2', '1', '4');
INSERT INTO `xuanze` VALUES (268, '灯泡功率在( )W及以上或潮湿场所用防潮封闭式灯具并用瓷质灯头。', '100', '200', '300', '60');
INSERT INTO `xuanze` VALUES (269, '带有电感式镇流器的荧光灯的功率因数为( )。', '0.4～0.6', '0.6～0.8', '0.8～1', '0.2～0.4');
INSERT INTO `xuanze` VALUES (270, '螺口灯座的顶芯应与( )连接。', '相线', '中性线', '保护线', '工作零线');
INSERT INTO `xuanze` VALUES (271, '螺口灯座的螺口应与( )连接。', '中性线', '保护地线', '相线', '保护零线');
INSERT INTO `xuanze` VALUES (272, '明装插座距地面不应低于( )m，暗装插座距地面不应低于0.3m。', '1.8', '1.3', '2', '1.5');
INSERT INTO `xuanze` VALUES (273, '翘板开关距出入口水平距离应为( )m。', '0.15～0.2', '0.3', '0.5', '0.4');
INSERT INTO `xuanze` VALUES (274, '单相三眼插座的 ( ) 应当接在保护线专用的接线端子上。', '保护线', '相线', '不接线', '工作零线');
INSERT INTO `xuanze` VALUES (275, '普通灯具与可燃物之间的距离不应小于( )m。否则，应采取隔热、散热措施。', '0.3', '0.1', '0.4', '0.2');
INSERT INTO `xuanze` VALUES (276, '生产场所室内吊灯采用100～150W白炽灯（有反射罩），灯具距地面最低悬挂高度一般不应小于( )m。', '2.5', '3', '2', '1.5');
INSERT INTO `xuanze` VALUES (277, '250W带有反射罩的高压荧光灯的高度不应小于( )m。', '5', '2.5', '3', '4');
INSERT INTO `xuanze` VALUES (278, '一般将( )V以下的线路称为低压线路。', '1000', '380', '500', '1200');
INSERT INTO `xuanze` VALUES (279, '电杆的埋深，一般情况可取杆长的( )+0.7m。', '1/10', '1/9', '1/7', '1/8');
INSERT INTO `xuanze` VALUES (280, '直线杆同杆架设的上、下层低压横担之间的最小距离不得小于( )m。', '0.6', '0.8', '0.4', '0.5');
INSERT INTO `xuanze` VALUES (281, '低压线路在同一横担架设时，面向负荷从左至右为：( )。', 'L1、N、L2、L3', 'L1、L2、N、L3', 'L1、L2、L3、N', 'N、L1、L2、L3');
INSERT INTO `xuanze` VALUES (282, '在人口密集地区，低压架空线路导线离地面的最小高度为( )m。', '6', '4.5', '5.5', '5');
INSERT INTO `xuanze` VALUES (283, '低压架空线路导线离建筑物的最小垂直距离为( )m。', '2.5', '1.5', '1', '2');
INSERT INTO `xuanze` VALUES (284, '低压架空线路导线离建筑物的最小水平距离为( )m。', '1.0', '0.6', '0.8', '1.2');
INSERT INTO `xuanze` VALUES (285, '低压架空线路导线与树木的最小水平距离（最大风偏情况）为( )m。', '1.0', '0.8', '1.2', '0.6');
INSERT INTO `xuanze` VALUES (286, '低压配电线路档距：城市市区40～50m，城郊及农村( )m。', '40～60m', '60～80m', '40～50m', '80～100m');
INSERT INTO `xuanze` VALUES (287, '低压接户线跨越交通要道，导线在最大弧垂时，离地面的最小高度为( )m。', '6', '5', '5.5', '4.5');
INSERT INTO `xuanze` VALUES (288, '低压接户线跨越交通困难的街道时，导线在最大弧垂时，离地面的最小高度为( )m。', '3.5', '5', '3', '4');
INSERT INTO `xuanze` VALUES (289, '接户线可由附杆引出，导线在( )mm²及以上时，应采用蝶式绝缘子固定。', '10', '16', '25', '6');
INSERT INTO `xuanze` VALUES (290, '当线路较长时，宜按( )确定导线截面。', '允许电压损失', '经济电流密度', '机械强度', '允许电流');
INSERT INTO `xuanze` VALUES (291, '按照机械强度的要求，北京城区低压架空线路。铝绞线、钢芯铝绞线的截面不得小于( )mm2。', '25', '10', '35', '16');
INSERT INTO `xuanze` VALUES (292, '普通拉线与地面的夹角不得大于( )。', '60º', '75º', '65º', '70º');
INSERT INTO `xuanze` VALUES (293, '为防止拉线遭受破坏，对拉线截面进行最低限制，钢绞线不应小于( )mm²。', '25', '35', '10', '16');
INSERT INTO `xuanze` VALUES (294, '电缆敷设前进行绝缘电阻测试，绝缘电阻不得低于( )MΩ（20℃）。', '10', '20', '7', '5');
INSERT INTO `xuanze` VALUES (295, '交联聚乙烯绝缘单芯电力电缆的最小弯曲半径不得小于电缆外径的( )倍。', '20', '15', '5', '10');
INSERT INTO `xuanze` VALUES (296, '交联聚乙烯绝缘多芯电力电缆的最小弯曲半径不得小于电缆外径的( )倍。', '15', '20', '10', '5');
INSERT INTO `xuanze` VALUES (297, '无铅包护套或无钢铠护套橡皮绝缘电力电缆的弯曲半径不得小于电缆外径的( )倍。', '10', '6', '2', '8');
INSERT INTO `xuanze` VALUES (298, '直埋电缆的最小埋设深度一般为( )m。', '0.7', '2', '0.6', '1');
INSERT INTO `xuanze` VALUES (299, '直埋电缆沟底电缆上、下应铺设厚( )mm的沙或软土。', '100', '50', '2', '150');
INSERT INTO `xuanze` VALUES (300, '直埋电缆应在拐弯、接头、交叉、进入建筑物等地段埋设标桩，应高出地面( )mm。', '150～200', '50～100', '300～400', '500');
INSERT INTO `xuanze` VALUES (301, '直埋电缆与热力管沟平行时，其间距离不得小于( )m。', '2', '0.5', '1', '1.5');
INSERT INTO `xuanze` VALUES (302, '直埋电缆与热力管沟交叉接近时，其间距离不得小于( )m。', '0.5', '1.5', '2', '1');
INSERT INTO `xuanze` VALUES (303, '直埋电缆与城市道路平行时，其间距离不得小于( )m。', '1', '2', '1.5', '0.7');
INSERT INTO `xuanze` VALUES (304, '电力电缆铝芯线的连接常采用( )。', '钳压法', '焊接法', '绑接法', '插接法');
INSERT INTO `xuanze` VALUES (305, '橡胶绝缘电缆工作温度不大于( )℃', '65', '70', '60', '80');
INSERT INTO `xuanze` VALUES (306, '各种明配线装置的水平高度距地面不应低于( )m，垂直敷设不应低于1.8m，距离不够时应加管保护。', '2.5', '2', '3', '1.8');
INSERT INTO `xuanze` VALUES (307, '( )配线不得使用铝导线配线。', '木槽板', '金属管', '冲压车间', '金属槽');
INSERT INTO `xuanze` VALUES (308, '( )配线不得使用铝导线配线。', '舞台照明', '塑料管', '冷作车间', '金属管');
INSERT INTO `xuanze` VALUES (309, '( )配线不得使用铝导线配线。', '剧烈振动的场所', '金属管', '办公室', '金属冷加工车间');
INSERT INTO `xuanze` VALUES (310, '槽板配线槽板规格应与导线规格和根数相适应，一般规定导线（含绝缘层）的总截面积不大于槽板内径( )。', '1/3', '1/4', '1/2', '1/5');
INSERT INTO `xuanze` VALUES (311, '管配线三条及以上绝缘导线穿于同一管内时，其总截面积不应超过管内截面积的( )。', '40％', '60％', '50％', '70％');
INSERT INTO `xuanze` VALUES (312, '电线管配线有一个90°弯者，每( )m应安装接线盒。', '20', '30', '50', '40');
INSERT INTO `xuanze` VALUES (313, '电线管配线有两个90°弯者，每( )m应安装接线盒。', '15', '20', '25', '30');
INSERT INTO `xuanze` VALUES (314, '电线管配线有三个90°弯者，每( )m应安装接线盒。', '8', '12', '20', '16');
INSERT INTO `xuanze` VALUES (315, '穿管的绝缘导线，铜线容许最小截面为1mm²、铝线容许最小截面为( )mm²。', '2.5', '1.5', '6', '4');
INSERT INTO `xuanze` VALUES (316, '临时用电工程、设施和设备应设立时间。超过( )以上应按正式工程和正式用电规定安装。', '6个月', '12个月', '9个月', '3个月');
INSERT INTO `xuanze` VALUES (317, '临时用电设备的控制电器和保护电器必须实现( )的安装方式。', '一机一闸', '三机一闸', '四机一闸', '二机一闸');
INSERT INTO `xuanze` VALUES (318, '施工现场内一般不得架设( )导线。', '裸体', '电缆', '绝缘', '架空');
INSERT INTO `xuanze` VALUES (319, '临时用电架空线路与施工建筑物的水平距离一般不得小于( )m。', '10', '2', '3', '5');
INSERT INTO `xuanze` VALUES (320, '临时用电与地面的垂直距离不得小于( )m。', '6', '3', '2.5', '5');
INSERT INTO `xuanze` VALUES (321, '临时用电跨越建筑物时与其顶部的垂直距离不得小于( )m。', '2.5', '2', '3', '3.5');
INSERT INTO `xuanze` VALUES (322, '塔式起重机附近的架空线路，应在臂杆回转半径及被吊物( )m以外。', '1.5', '1', '0.8', '2');
INSERT INTO `xuanze` VALUES (323, '临时用电电气设备的接地线或接保护线应使用( )。', '多股铜线', '多股铝线', '钢筋', '钢绞线');
INSERT INTO `xuanze` VALUES (324, '施工现场及临时生活区高度在( )m及以上应装设防雷保护装置，并及时用导线与建筑物接地线连接。', '20', '10', '25', '15');
INSERT INTO `xuanze` VALUES (325, '塔式起重机的轨道，一般应设两组接地装置；对塔线较长的轨道，每隔( )m应补做一组接地装置。', '20', '15', '40', '30');
INSERT INTO `xuanze` VALUES (326, '配电箱、盘的操作面上的操作部位不得有( )明露。', '带电体', '相线', '中性线', '保护线');
INSERT INTO `xuanze` VALUES (327, '具有三个及以上回路的配电箱、盘应装设( )。', '总开关', '熔断器', '刀闸', '接触器');
INSERT INTO `xuanze` VALUES (328, '光力合一的流动配电箱，一般应装设( )剩余电流动作保护开关或防中性线断线的安全保护装置。', '四极', '三极', '一极', '二极');
INSERT INTO `xuanze` VALUES (329, '用电设备至配电箱之间的距离，一般不应大于( )m。', '5', '10', '3', '15');
INSERT INTO `xuanze` VALUES (330, '固定式配电箱至流动闸箱之间的距离，最大不应超过( )m。', '40', '50', '20', '30');
INSERT INTO `xuanze` VALUES (331, '弧焊机的电源线上应装设有( )。', '隔离电器、主开关、短路保护漏电保护器', '主开关和短路保护电器', '隔离电器和主开关', '隔离电器和短路保护电器');
INSERT INTO `xuanze` VALUES (332, '采用潜水泵排水时其半径( )m水域内不得有人作业。', '30', '10', '20', '40');
INSERT INTO `xuanze` VALUES (333, '临时设施的照明灯具对地面垂直距离不应低于2.5m，室外不应低于( )m。', '3', '2.5', '4', '3.5');
INSERT INTO `xuanze` VALUES (334, '暂设灯头与易燃烧物的净具一般不小于300mm，聚光灯、碘钨灯等高热灯具与易燃物应保持安全距离，一般不小于( )mm。', '500', '600', '400', '300');
INSERT INTO `xuanze` VALUES (335, '钢索配线间距不大于( )m，护套线配线允许直接敷设于钢索上。', '12', '10', '20', '15');
INSERT INTO `xuanze` VALUES (336, '暂设高温灯具安装高度不低于( )m，灯线应固定在接线柱上，不得靠近灯具。', '5', '3.5', '4', '2.5');
INSERT INTO `xuanze` VALUES (337, '雷电流幅值指主放电时冲击电流的最大值。雷电流幅值可达( )。', '数十至数百千安', '数十至数百安', '数至数千安', '数至数十千安');
INSERT INTO `xuanze` VALUES (338, '每次雷击有三四个冲击至数十个冲击。一次直击雷的全部放电时间一般不超过( )ms。', '500', '100', '800', '600');
INSERT INTO `xuanze` VALUES (339, '防直击雷装置由( )组成。', '接闪器、引下线、接地装置', '熔断器、引下线、接地装置', '接闪器、断路器、接地装置', '接闪器、引下线、电容器');
INSERT INTO `xuanze` VALUES (340, '附设接闪器每根引下线的冲击接地电阻不应大于( )Ω。', '10', '20', '30', '4');
INSERT INTO `xuanze` VALUES (341, '防直击雷的人工接地体距建筑物出入口和人行道不应小于( )m。', '3', '2', '1.5', '1');
INSERT INTO `xuanze` VALUES (342, '避雷器属于( )保护元件。', '过电压', '过负载', '接地', '短路');
INSERT INTO `xuanze` VALUES (343, '避雷器的作用是防止( )的危险。', '雷电波侵入', '电磁感应雷', '静电感应雷', '直击雷');
INSERT INTO `xuanze` VALUES (344, 'FS系列阀型避雷器主要由( )组成。', '瓷套、火花间隙、非线性电阻', '瓷套、电容器、非线性电阻', '瓷套、火花间隙、熔断器', '断路器、火花间隙、非线性电阻');
INSERT INTO `xuanze` VALUES (345, '氧化锌避雷器采用( )密封于绝缘套中。', '氧化锌电阻片', '固定电阻', '热敏电阻', '可变电阻');
INSERT INTO `xuanze` VALUES (346, '独立避雷针的冲击接地电阻一般不应大于( )Ω。', '10', '4', '30', '1');
INSERT INTO `xuanze` VALUES (347, '标准上规定防雷装置的接地电阻一般指( )电阻。', '冲击', '高频', '直流', '工频');
INSERT INTO `xuanze` VALUES (348, '避雷器属于对( )的保护元件。', '雷电冲击波', '静电感应雷', '电磁感应雷', '直击雷');
INSERT INTO `xuanze` VALUES (349, '防雷装置的引下线地下0.3m至地上( )m的一段应加保护。', '1.7', '1.0', '2.4', '0.5');
INSERT INTO `xuanze` VALUES (350, '静电现象是一种常见的带电现象，可达( )伏。', '上万', '数十', '数百', '数千');
INSERT INTO `xuanze` VALUES (351, '在具有爆炸性粉尘或爆炸性气体、蒸气的场所，例如（ ），可能由静电火花引起爆炸。', '煤粉、面粉、铝粉、氢气', '木材', '金属', '朔料');
INSERT INTO `xuanze` VALUES (352, '单纯为了消除导电体上的静电，接地电阻（ ）Ω。', '100Ω', '10Ω', '30Ω', '5Ω');
INSERT INTO `xuanze` VALUES (353, '消除静电增湿法就是提高空气的湿度，保持相对湿度在（ ）％以上较为适宜。', '50', '30', '60', '40');
INSERT INTO `xuanze` VALUES (354, '防止电击事故的措施分( )类。', '三', '二', '一', '四');
INSERT INTO `xuanze` VALUES (355, '第( )类是间接接触电击防护措施。', '二', '四', '一', '三');
INSERT INTO `xuanze` VALUES (356, '测量额定电压500V以下的线路或设备的绝缘电阻，应采用工作电压为( )V的兆欧表。', '500～1000', '100', '50', '2500');
INSERT INTO `xuanze` VALUES (357, '携带式电气设备的绝缘电阻不应低于( )MΩ。', '2', '5', '1', '0.5');
INSERT INTO `xuanze` VALUES (358, '遮栏与裸导体之间的距离不应小于( )m。', '0.8', '0.35', '0.7', '1.0');
INSERT INTO `xuanze` VALUES (359, '通信线路与低压线路之间的距离不得小于( )m。', '1.5', '1.0', '2.0', '1.2');
INSERT INTO `xuanze` VALUES (360, '低压接户线跨越通车街道时，对地距离不应小于( )m。', '6.0', '5.0', '3.5', '4.5');
INSERT INTO `xuanze` VALUES (361, '在低压工作中，人体或其所携带工具与带电体的距离不应小于( )m。', '0.1', '0.7', '0.3', '0.5');
INSERT INTO `xuanze` VALUES (362, '对于加强绝缘的电气设备，带电部件与可触及导体间的绝缘电阻不应低于( )MΩ。', '7', '1', '2', '0.5');
INSERT INTO `xuanze` VALUES (363, '绝缘材料是依据( )分级的。', '耐热性能', '耐弧性能', '阻燃性能', '绝缘电阻');
INSERT INTO `xuanze` VALUES (364, 'E级绝缘的允许工作温度为( )℃。', '120', '95', '105', '130');
INSERT INTO `xuanze` VALUES (365, 'B级绝缘的允许工作温度为( )℃。', '130', '95', '105', '120');
INSERT INTO `xuanze` VALUES (366, '测量绝缘电阻的仪表是( )。', '兆欧表', '双臂电桥', '接地电阻测量仪', '单臂电桥');
INSERT INTO `xuanze` VALUES (367, 'Ⅱ类设备是具备( )特征的设备。', '双重绝缘', '漏电保护', '裸露金属件上有接地端子', '安全电压');
INSERT INTO `xuanze` VALUES (368, 'Ⅲ类设备是具备( )特征的设备。', '安全电压', '双重绝缘', '裸露金属件上有接地端子', '漏电保护');
INSERT INTO `xuanze` VALUES (369, '工作绝缘是( )。', '保证设备正常工作和防止触电的基本绝缘', '不可触及的导体与可触及的导体之间的绝缘', '带电体与地之间的绝缘', '可触及的导体与带电体之间的绝缘');
INSERT INTO `xuanze` VALUES (370, '保护绝缘是( )。', '工作绝缘损坏后用于防止触电的绝缘', '带电体与地之间的绝缘', '不可触及的导体与带电体之间的绝缘', '可触及的导体与带电体之间的绝缘');
INSERT INTO `xuanze` VALUES (371, '双重绝缘是指( )。', '工作绝缘和保护绝缘', '不可触及的导体与带电体之间的绝缘', '不可触及的导体与可触及的导体之间的绝缘', '带电体与地之间的绝缘');
INSERT INTO `xuanze` VALUES (372, '在金属容器内使用的手提照明灯的电压应为( )V。', '12', '36', '220', '24');
INSERT INTO `xuanze` VALUES (373, '作为安全电压的电源变压器应当采用( )变压器。', '双线圈', '电力', '单绕组', '自耦');
INSERT INTO `xuanze` VALUES (374, '安全隔离变压器输入回路与输出回路之间的绝缘电阻不应低于( )MΩ。', '7', '2', '5', '0.5');
INSERT INTO `xuanze` VALUES (375, '高灵敏度电流型漏电保护装置是指额定漏电动作电流( )mA及以下的漏电保护装置。', '30', '15', '6', '10');
INSERT INTO `xuanze` VALUES (376, '漏电保护器后方的线路的零线只允许连接( )线。', '用电设备的工作零线', '地', 'PE', 'PEN');
INSERT INTO `xuanze` VALUES (377, '安装漏电保护器时，( )线应穿过保护器的零序电流互感器。', 'N', 'PEN', 'PE', '接地');
INSERT INTO `xuanze` VALUES (378, '( )mA以上的属低灵敏度，用于防止漏电火灾和监视一相接地故障。', '1000', '200', '100', '300');
INSERT INTO `xuanze` VALUES (379, '用于防止漏电火灾的剩余电流动作保护装置的动作电流可在( )mA范围内选择。', '100～500mA', '75', '30', '50');
INSERT INTO `xuanze` VALUES (380, '电子式剩余电流动作保护装置，根据电子元器件有效工作寿命要求，工作一般为( )年。', '6', '3', '10', '5');
INSERT INTO `xuanze` VALUES (381, '《中华人民共和国安全生产法》规定，从业人员有权拒绝（）和强令冒险作业。', '违章指挥', '错误指挥', '应急指挥', '违章作业');
INSERT INTO `xuanze` VALUES (382, '《中华人民共和国安全生产法》规定，生产经营单位应当在有较大危险因素的生产经营场所和有关设施、设备上，设置明显的安全（）。', '警示标志', '指令标志', '禁止标志', '指示标志');
INSERT INTO `xuanze` VALUES (383, '《中华人民共和国安全生产法》规定，国家对严重危及生产安全的工艺、设备实行（）制度。', '淘汰', '年检', '定期保养', '定期维护');
INSERT INTO `xuanze` VALUES (384, '《中华人民共和国安全生产法》规定，危险物品的生产、经营、储存单位以及矿山、（ ）、城市轨道交通运营、建筑施工单位应当建立应急救援组织。', '金属冶炼', '高处施工', '金属加工', '制冷企业');
INSERT INTO `xuanze` VALUES (385, '《中华人民共和国安全生产法》规定，生产经营单位发生生产安全事故后，事故现场有关人员应当立即报告（ ）。', '本单位负责人', '安全主管', '现场负责人', '安全技术人员');
INSERT INTO `xuanze` VALUES (386, '《中华人民共和国安全生产法》规定，生产经营单位的从业人员有权了解的内容，不包含（ ）项。', '安全生产投入预算', '事故应急措施', '防范措施', '场所和工作岗位存在的危险因素');
INSERT INTO `xuanze` VALUES (387, '《中华人民共和国安全生产法》规定，任何单位和个人不得（ ）对事故的依法调查处理。', '阻挠和干涉', '阻止和妨碍', '阻挠和妨碍', '妨碍和干涉');
INSERT INTO `xuanze` VALUES (388, '《中华人民共和国安全生产法》规定，国家对严重危及生产安全的工艺、设备实行（ ）制度。', '淘汰', '定期保养', '年检', '定期维护');
INSERT INTO `xuanze` VALUES (389, '《中华人民共和国安全生产法》规定，生产经营单位必须为从业人员提供符合（ ）的劳动防护用品，并监督、教育从业人员按照使用规则佩戴、使用。', '国家标准或者行业标准', '国际标准或者卫生标准', '卫生标准或者技术标准', '管理标准或者地方标准');
INSERT INTO `xuanze` VALUES (390, '《中华人民共和国安全生产法》规定，从业人员有权拒绝（ ）和强令冒险作业。', '违章指挥', '应急指挥', '违章作业', '错误指挥');
INSERT INTO `xuanze` VALUES (391, '《中华人民共和国安全生产法》规定，生产经营单位与从业人员订立的劳动合同，应当载明有关保障从业人员（ ）、防止职业危害，以及为从业人员办理工伤保险事项。', '劳动安全', '劳动权利', '教育和培训', '福利待遇');
INSERT INTO `xuanze` VALUES (392, '《中华人民共和国安全生产法》规定，生产经营单位发生生产安全事故时，单位的（ ）应当立即组织抢救，并不得在事故调查处理期间擅离职守。', '主要负责人', '技术人员', '现场负责人', '安全管理人员');
INSERT INTO `xuanze` VALUES (393, '《中华人民共和国安全生产法》规定，生产经营单位对（ ）应当登记建档，进行定期检测、评估、监控，并制定应急预案，告知从业人员和相关人员在紧急情况下应当采取的应急措施。', '重大危险源', '事故隐患', '危险源', '重大事故隐患');
INSERT INTO `xuanze` VALUES (394, '《中华人民共和国安全生产法》规定，安全设备的设计、制造、安装、使用、检测、维修、（ ），应当符合国家标准或者行业标准。', '改造和报废', '维护和保养', '改造和维护', '保养和改造');
INSERT INTO `xuanze` VALUES (395, '《中华人民共和国安全生产法》规定，生产经营单位应当在有较大危险因素的生产经营场所和有关设施、设备上，设置明显的安全（ ）。', '警示标志', '指示标志', '禁止标志', '指令标志');
INSERT INTO `xuanze` VALUES (396, '《中华人民共和国安全生产法》规定，生产经营单位的特种作业人员必须按照国家有关规定，经专门的安全作业培训，取得（），方可上岗作业。', '相应资格', '特种作业操作证书', '特种作业操作资格证书', '职业技能等级证书');
INSERT INTO `xuanze` VALUES (397, '《中华人民共和国安全生产法》规定，生产经营单位采用新工艺、新技术、新材料或者使用新设备，必须了解、掌握其安全技术特性，采取有效的（ ），并对从业人员进行专门的安全生产教育和培训。', '安全防护措施', '安全技术措施', '安全管理措施', '个体防护措施');
INSERT INTO `xuanze` VALUES (398, '《中华人民共和国安全生产法》规定，生产经营单位必须建立、健全安全生产责任制度和安全生产规章制度，改善安全生产条件，加强（ ），提高安全生产水平。', '安全生产标准化、信息化建设', '事故预防体系建', '企业安全文化建设', '隐患排查治理体系建');
INSERT INTO `xuanze` VALUES (399, '《中华人民共和国安全生产法》规定，安全生产工作应当以人为本，坚持（ ）的方针。', '安全第一、预防为主、综合治理', '安全第一、人人有责', '安全第一、以人为本', '安全第一、预防为主');
INSERT INTO `xuanze` VALUES (400, '《全国人民代表大会常务委员会关于修改〈中华人民共和国安全生产法〉的决定》已由中华人民共和国第十三届全国人民代表大会常务委员会第二十九次会议于2021年6月10日通过，自2021年（ ）起施行。', '9月1日', '10月1日', '11月1日', '8月31日');
INSERT INTO `xuanze` VALUES (401, '《北京市安全生产条例》规定，生产经营单位进行悬吊、挖掘、油罐清洗、建设工程拆除、高处作业、临近高压输电线路作业、有限空间作业等，应当安排负责现场管理的（ ），确认现场作业条件、作业人员的上岗资质、身体状况符合安全作业要求。', '专门人员', '技术人员', '安全管理人员', '普通人员');
INSERT INTO `xuanze` VALUES (402, '北京市安全生产条例》规定，生产经营单位的主要负责人应当依照安全生产法的规定，组织落实全员（ ），明确各岗位的责任人员、责任范围和考核标准等内容，并加强对落实情况的监督考核。', '安全生产责任制', '安全生产管理体系', '安全生产规章制度', '安全生产管理职责');

SET FOREIGN_KEY_CHECKS = 1;
